### ISSUE TITLE
[BUG] The select is not load value when it is in datagrid

### ISSUE THREAD

**Issue by QThans** [formio/formio.js#3041] opened 2020-07-14 18:23 UTC
i create a datagrid,and create a select in this.
When i have setting this select,the lazyLoad is true,it is load from resource.

When I click datagrid‘s add-another,select  in the added row has no loaded value.

**Comment by wag110894** [comment] 2020-07-14 19:25
@QThans,
Thank you for reaching out! We are unable to replicate this using version 4.11.0-rc.4 of the formio.js renderer. What version are you running? 

Can you also provide a JSFiddle or a form embed for this issue?

Thank you.

**Comment by QThans** [comment] 2020-07-15 06:30
https://jsfiddle.net/thans/e3z7oLpn

@wag110894 

I have using version 4.11.0 replicate this.
Is my api error?
But,If i click the select,It will be loading and setting value.You test it.Only when i  add row,the value will be display.

**Comment by wag110894** [comment] 2020-07-20 15:43
@QThans Thank you for providing the JSfiddle of this issue but we are not able to reproduce this outside of your JSFiddle. We do have support packages, which will allow you to connect with our developers to see what is going on in your form. For more information, please contact support@form.io.

Thank you.

**Comment by Tatsiana8** [comment] 2024-01-31 14:54
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by Tatsiana8** 2024-01-31 14:54 UTC
Labels: bug
