### ISSUE TITLE
[BUG] HTML Element Component

### ISSUE THREAD

**Issue by piloop35** [formio/formio.js#2168] opened 2019-12-09 14:52 UTC
reopen : https://github.com/formio/formio.js/issues/1389

## Environment

- Hosting type
  - [x] Form.io
  - [x] Local deployment
- Formio.js version: ^4.8.0-rc.1
- Frontend framework: vueJS
- Browser: Chrome
- Browser version:  78.0.3904.97

## Steps to Reproduce
1. Create an HTML component with  an attribute href with  {{data.url}}
2. In the submission, add:
"submission = {
    data: {
    url: "www.github.com"
     }
  }"

## Expected behavior
` <a href="www.github.com" ref="html" class="">test</a>`

## Observed behavior
`<a href="{{data.url}}" ref="html" class="">test</a>`

## Example
http://jsfiddle.net/fabienfeat/5w94gkhx/

Step 1:
<a href="https://zupimages.net/viewer.php?id=19/50/l08y.png"><img src="https://zupimages.net/up/19/50/l08y.png" alt="" /></a>

Step 2:
<a href="https://zupimages.net/viewer.php?id=19/50/czrh.png"><img src="https://zupimages.net/up/19/50/czrh.png" alt="" /></a>

**Comment by jhen1422** [comment] 2019-12-09 16:23
@piloop35 Thank you for the report. We have reviewed this issue and added to our 4x backlog. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by alexmaie** [comment] 2020-06-23 07:37
Hello FormIO team,

We also noticed the same issue with <img> tag in the html component.
Did you already manage to advance with this bug?

Thanks
Alex

**Comment by wag110894** [comment] 2020-06-23 13:41
Hello @alexmaie,

This is item is still in our 4x backlog. We do welcome a Pull request for this item. If you do need this item expedited, then contact support@form.io for pricing. The ticket you can reference is FJS-597.

**Comment by ranjwarrior** [comment] 2023-07-12 13:49
Hello @wag110894,
Is this issue fixed? I think I still see this bug in v4.15.0-rc.19.
Thanks!

**Comment by lane-formio** [comment] 2024-01-31 21:23
@piloop35 @ranjwarrior 
I couldn't find where this was fixed. But I couldn't reproduce in formiojs@4.18.1

Closing the issue for now, but please reopen if you believe this to still be relevant in our latest release.

**Closed by lane-formio** 2024-01-31 21:23 UTC
Labels: bug
