### ISSUE TITLE
[BUG] Typing into multiple-values Resource field: last letter not visible half of the time

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#1244] opened 2019-05-10 11:01 UTC
- Add a "resource" component with "multiple-values".
- Repeatedly type the letter 'l' or the letter 'i' into the component.
- Observe that for even letter counts, the last letter is not visible, which is irritating to the user.
- But all typed letters are in fact present in the field (checked with select-all & copy/paste).
- Observed with Firefox 66.0.4. Not broken on Chromium 73.0.3683.86

**Comment by franke-mc** [comment] 2019-06-24 13:10
Tested with Firefox 67.0.3:
- Occurs in "Edit" or "Use" mode of form on beta.form.io .
- Does NOT occur on launched form: https://formview.io/#/benudbjfljpobfo/testtags&header=1

**Comment by randallknutson** [comment] 2019-06-24 15:35
This is very strange. Have you tried using the select component with the data source of "Resource"?

**Comment by franke-mc** [comment] 2019-06-24 15:59
The test was already using the select component with the data source of "Resource". It's the same using the "Resource" component. (I have added the "Resource" variant to the form above, but as stated, it does not occur in the "launched" version, only in the "Edit" or "Use" cases.)

**Comment by wag110894** [comment] 2019-06-26 13:57
Andreas,

Thanks for reaching out!

We are able to replicate this issue using Firefox. We have created a ticket (FOR-2408) and have tagged you on it. We will let you know once the issue is resolved.

Thanks!

**Comment by aiwebb** [comment] 2019-07-01 18:00
@franke-mc, I tracked this down to a bug in one of our dependencies. I've submitted a fix for it upstream, and we'll keep an eye on it over the next couple of days to see if it gets merged in so we can update our version.

**Comment by franke-mc** [comment] 2019-10-29 23:19
Thank you @aiwebb. Just to document what's going on: You were talking about [PR #608](https://github.com/jshjohnson/Choices/pull/608) for upstream [issue #607](https://github.com/jshjohnson/Choices/issues/607). It appears to have been merged into master with [this commit](https://github.com/jshjohnson/Choices/commit/39b6eed395be7b9f4ec9e69c4eb46a326d9cf701#diff-903ef4d04f295561e0d55c0c97aa11b3) on October 2nd, followed by complete removal of that function on October 28th in [this commit](https://github.com/jshjohnson/Choices/commit/dbd15d7823f0017c8b981a889061c8efeaa48e36#diff-903ef4d04f295561e0d55c0c97aa11b3) from [PR #694](https://github.com/jshjohnson/Choices/pull/694). I hope the fix is preserved that way.

**Closed** 2022-09-29 16:37 UTC
