### ISSUE TITLE
Radio Buttons with numeric values aren't working

### ISSUE THREAD

**Issue by andycanterbury** [formio/formio.js#202] opened 2017-10-02 15:03 UTC
If a required radio button has numbers for the values, when the form is submitted, the radio button's selection is cleared and the form errors. 
Setup:
![de4406 radio buttons setup](https://user-images.githubusercontent.com/10052615/31083573-0813888e-a760-11e7-89e0-853f3e342641.PNG)

Error: 
![de4406 radio button error](https://user-images.githubusercontent.com/10052615/31083962-21964bec-a761-11e7-88e2-49295a255347.gif)

**Comment by travist** [comment] 2017-10-03 01:53
What I am seeing is that the submission actually goes through just fine, but the issue is that the form is invalidating after it is submitted. If this is the same issue you are seeing, then this will be fixed with next push.

**Comment by andycanterbury** [comment] 2017-10-03 13:14
I do see the submission happening, but the value isn't passed along. 
"submission":{"page1Gender":"","submit":[]}

**Comment by travist** [comment] 2017-10-08 03:34
I just pushed up version 2.19.0. Please verify that this has been fixed.

**Closed by travist** 2017-10-08 03:34 UTC
