### ISSUE TITLE
[BUG] Layout columns, delete column does not work

### ISSUE THREAD

**Issue by ssrini** [formio/formio.js#1422] opened 2019-06-26 12:24 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: Latest
- Formio.js version: Latest
- Frontend framework: JS
- Browser: Chrome
- Browser version: Latest

## Steps to Reproduce

1.  Use the sample code in https://github.com/formio/formio.js to display the builder or the hosted demo at https://formio.github.io/formio.js/app/builder
2. Open Layout and add column layout
3.  In the popup add a third column (default is 2) and Save
4.  Now edit the layout again and delete the third column and save.  In the layout the column still appears

## Expected behavior
1.  The deleted column should not appear

## Example
This happens with the sample code to display the builder so no special code needed.  This is actually identical to the Closed issue #552

**Comment by ssrini** [comment] 2019-06-26 12:35
I can confirm that this works on form.io cloud with the free account

**Comment by randallknutson** [comment] 2019-06-26 14:49
You have the formio.js version marked as "Latest" is that the latest stable (v3.22.9) or latest beta (v4.0.0-beta.53)?

**Comment by ssrini** [comment] 2019-06-26 18:01
3.22.9. Note that this also occurs in the formio demo

**Comment by wag110894** [comment] 2019-06-26 22:09
Hello,

We have tagged you in the ticket(FOR-2172) for this issue. We will let you know once this issue is resolved. 

Thanks for reaching out!

**Comment by jhen1422** [comment] 2019-07-28 23:41
@ssrini  Can you please confirm if this is still an issue for you? Unable to replicate on our end.

**Comment by srinisubramanian** [comment] 2019-07-29 06:35
@jhen1422 This is still an issue with the version 3.24.0.  I just tested it with the sample code for a builder on your Github readme.me (reproduced below)

```
<html>
  <head>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://unpkg.com/formiojs@latest/dist/formio.full.min.css'>
    <script src='https://unpkg.com/formiojs@v3.24.0/dist/formio.full.min.js'></script>
    <script type='text/javascript'>
      window.onload = function() {
        Formio.builder(document.getElementById('builder'));
      };
    </script>
  </head>
  <body>
    <div id='builder'></div>
  </body>
</html>
```
Steps:

1.  Open a new form builder
2.  Add a column layout (default 2 columns of 6 each are added)
3.  Delete a column (only 1 column is left now) and press Save in the popup
4.  The builder still displays 2 columns

Hope this helps

**Comment by srinisubramanian** [comment] 2019-07-29 06:39
Here are some screenshots of the example:

With 2 columns:
![image](https://user-images.githubusercontent.com/8343179/62026751-8356fd00-b1f9-11e9-8398-fb256a3e104d.png)

Deleting 1 column and changing width (to demonstrate the issue)
![image](https://user-images.githubusercontent.com/8343179/62026797-9d90db00-b1f9-11e9-8c35-82423472e281.png)

Still 2 columns are displayed (one of 12 and the other of width 6)

![image](https://user-images.githubusercontent.com/8343179/62026829-b8fbe600-b1f9-11e9-8eaa-01f2fd7eedab.png)

**Comment by randallknutson** [comment] 2019-07-29 14:53
Duplicate of https://github.com/formio/formio.js/issues/552

**Closed by randallknutson** 2019-07-29 14:53 UTC
Labels: bug

**Comment by franke-mc** [comment] 2019-07-29 15:43
@randallknutson: Now both this issue as well as #552 are closed as this should be fixed in 4.x.  Which issue is supposed to track the bug in 3.x now?

**Comment by chaseven** [comment] 2020-04-21 05:38
Hi guys, having the same issue here on version 3.x no sign of any fix. Have tested on version 4 and it looks fine there (unfortunately updating library is not an option for me).

Here a jsfiddle using version 3.29.11 (latest 3.x available until the moment) 
[https://jsfiddle.net/kvu1o028/1/](url)

So no matter what once you add a "column layout" the only way to remove a column from it is by removing the whole component.

Should I create a new issue or is it possible to reopen this one? If not could you just confirm that this will not be fixed on the version 3.x?

Cheers

**Comment by travist** [comment] 2020-04-21 13:55
Since we already have a fix in 4.x for this item, I am afraid this will not get resolved by the Form.io team without either someone from the community submitting a pull request, or someone paying to expedite the fix. We are currently fully bogged down supporting and making 4.x solid so just trying to be realistic with expectations on this getting fixed.

**Comment by chaseven** [comment] 2020-04-21 23:01
> Since we already have a fix in 4.x for this item, I am afraid this will not get resolved by the Form.io team without either someone from the community submitting a pull request, or someone paying to expedite the fix. We are currently fully bogged down supporting and making 4.x solid so just trying to be realistic with expectations on this getting fixed.

Thanks, for the reply @travist , that sets the expectation which was exactly what I needed.  About "paying to expedite the fix" how much that would be? Is there a pricing section where I can check this kind of things?

**Comment by wag110894** [comment] 2020-04-22 13:55
Please contact support@form.io for pricing on expediting this fix.
