### ISSUE TITLE
[BUG] html element sets a "ref=html" attribute

### ISSUE THREAD

**Issue by Johse** [formio/formio.js#2542] opened 2020-03-17 20:19 UTC
## Environment
v4.90 rc9

## Expected behavior
I would expect it to render to:
`<a href="path/to/image.jpg"><img alt="caption" src="path/to/image.jpg"></a>`

## Observed behavior
But it renders to: 
`<a href="path/to/image.jpg" ref="html"><img alt="caption" src="path/to/image.jpg"></a> `

Leading to the link being interpreted as a Document and not by its correct mime-type.

## Example
```js
        {
            "label": "HTML",
            "tag": "a",
            "attrs": [
                {
                    "attr": "href",
                    "value": "path/to/image.jpg"
                }
            ],
            "content": "<img src=\"path/to/image.jpg\" alt=\"caption\">",
            "refreshOnChange": false,
            "tableView": false,
            "key": "html",
            "type": "htmlelement",
            "input": false
        }
```

**Comment by randallknutson** [comment] 2020-03-17 20:32
This is interesting. I checked the spec for anchor tags (https://www.w3schools.com/tags/tag_a.asp and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) and it doesn't define ref anywhere that I see. There is "href" and "rel" but not ref. I wonder if a browser is trying to fix the misspelling or something. If not, the ref should not actually do anything in the browser like changing the mime-type. Can you try using "p" or something from the element type and then setting the anchor tag in the contents? That would eliminate the ref attribute as the cause of the issue.

**Comment by VikkiAlenn** [comment] 2024-01-31 14:34
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed** 2024-01-31 14:35 UTC
Labels: bug
