### ISSUE TITLE
[BUG] Textarea resizes on every key press when used in grid

### ISSUE THREAD

**Issue by dkwiebe** [formio/formio.js#4160] opened 2021-06-22 17:56 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: Greater than 4.9.0-rc.11
- Frontend framework: Bootstrap 4
- Browser: Chrome / Edge / Firefox
- Browser version: Chrome 91.0.4472.106 / Edge 91.0.864.54

## Steps to Reproduce
1.  Create text area inside of grid.  The first row will appear fine.
2.  Create second row and enter data in text area.

## Expected behavior
This fiddle shows the expected behaviour.  It functions correctly until version 4.9.0-rc.11 https://jsfiddle.net/dkwiebe/yL14nbfq/11/
![rint](https://user-images.githubusercontent.com/1034679/122975581-ba37de00-d350-11eb-8d7e-9a36919dd53c.gif)

## Observed behavior
When entering data in a textarea that is embedded in a grid, the resize functionality fires on every input.  This causes the screen to jump around excessively.

## Example
![iDW3SiC3wK](https://user-images.githubusercontent.com/1034679/122974962-19492300-d350-11eb-86a1-2d3ea11d9461.gif)
Illustrates problem: https://jsfiddle.net/dkwiebe/te5v67bh/17/

**Comment by airarrazaval** [comment] 2021-07-15 03:27
Ok, so this is one of those border cases.  If we simplify the problem to its simplest form we don't see the issue:

https://jsfiddle.net/airarrazaval/9Lru6x3b/.

Now, after playing around I found that the console throws the following warning:

![image](https://user-images.githubusercontent.com/9391489/125721210-ffc5345f-bcd6-4cbf-9a1c-f3edc24802fa.png)

It seems that row components are built with the same element id.  I assume that the autoexpand mechanism is triggered at the element identified by its unique id, but because the id is duplicated, it is triggered in all text areas inside the data grid independent if the value has changed or not.

In fact, the triggered component id is passed in the `triggeredComponentId` flag.

https://github.com/formio/formio.js/blob/def16e2873f71948101644ea35ec201bfa7b9f58/src/components/_classes/component/Component.js#L2737-L2740

I don't know if this is the culprit, but in the working example (formiojs@4.9.0-rc.11) there are no warning messages about duplicated ids.

**Comment by airarrazaval** [comment] 2021-07-15 21:25
So on further investigation, this only happens for components inside a columns (or any layout component) inside a data grid.  When data grids creates their rows they call the `createRowComponents` function.  Then, for every component they create (for each column and row) they set the component id to `component.id + rowIndex`.  The `component.id` is a unique id created for each component (and should be unique when generating copies of them in nested components).

https://github.com/formio/formio.js/blob/7714d49508e326636a2b78d6706cffcf9e80b126/src/components/datagrid/DataGrid.js#L533-L564

The issue is the following.  A component directly inside a Data Grid will update their id accordingly and will remain unique.  Now, if you have a nested component as direct child of the data grid, it will have a unique id (as data grid will assign a correct unique id).  The issue is when the other nested component renders its components, if it doesn't check before if he is in a nested component itself, then it will not bother creating unique ids for its child components (in his context he doesn't know he is inside a row).

I am going to look further into it and see if I can manage to find a quick fix for this.

**Comment by airarrazaval** [comment] 2021-07-16 02:25
Ok so definitely the id duplication has nothing to do with this bug (but it is something to fix).  v4.9.0-rc.12 introduced 2 changes:

* [Ensure that the hasChanged is always called even for layout components.](https://github.com/formio/formio.js/commit/f100fef0db8186613a7eb0ded69ca18ca132c6f6#diff-8795d5891ca105e3583ef74383eb1929aeec1fa888d641a0d7be8a91a0abd5f4)
* [Fixing the changed flag to pass from parent components. Fixes many issues regarding the changed states.](https://github.com/formio/formio.js/commit/661cf88e652e3162a0bd7e06b86a6afe09828f62#diff-8795d5891ca105e3583ef74383eb1929aeec1fa888d641a0d7be8a91a0abd5f4)

Before v4.9.0-rc.12 layout components inside nested components such as data grids were not checked for changes as it always returned false:

https://github.com/formio/formio.js/blob/e1a6bffe02c4767566bbf017989e8707581742fa/src/components/_classes/nested/NestedComponent.js#L481-L483

Because the components in your data grid were contained in a layout component (columns), the has changed was not triggered to all nested components (only the current row was affected).

After the change, the changed flag is properly being passed, and thus the redraw is triggered.  I think the effect that is shown is a product of the  `addAutoExpand` function (before the change it was not triggered).

https://github.com/formio/formio.js/blob/7714d49508e326636a2b78d6706cffcf9e80b126/src/components/textarea/TextArea.js#L410-L487

If you check the very end you will see to which events the `update` function is attached to:

https://github.com/formio/formio.js/blob/7714d49508e326636a2b78d6706cffcf9e80b126/src/components/textarea/TextArea.js#L483-L486

I think the change flag that is passed down even on layout components inside the data grid reinitializes all rows components, thus the resize is triggered on all rows.

**Comment by olgabann** [comment] 2024-02-14 11:02
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by olgabann** 2024-02-14 11:02 UTC
Labels: bug
