### ISSUE TITLE
checkValidity can not valid wizard inactive page value

### ISSUE THREAD

**Issue by huzech** [formio/formio.js#1535] opened 2019-08-02 11:18 UTC
form.checkValidity works well in single form, but not works in wizard type.
I set form.setPristine(false);
for example
set wizard type with page1,page2,page3, switch to page2 and fire form.checkValidity(form.submission.data), but it's not valid element in page1 and page3, only valid element page2.
so how can do it.

**Comment by randallknutson** [comment] 2019-08-02 14:41
In the 3.x version of our renderer the only items that are instantiated and checked in checkValidity is the current page. In the 4.x branch it will check all pages. Are you using the 3.x or 4.x version of the renderer?

**Comment by huzech** [comment] 2019-08-04 01:15
Thanks! I'm Using 3.x, And any plan to add this function to 3.x?

**Comment by randallknutson** [comment] 2019-08-05 15:27
Unfortunately the difference is a fundamental way that the 3.x version was designed. This is one of the reasons we changed this for 4.x. In order to backport this we would basically have to make it work like 4.x. You may want to try upgrading to 4.x and see how it works for you.

**Comment by huzech** [comment] 2019-08-06 06:00
Dose any documents about 4.x available? I tested 4.x and found some difference of Apis.

**Comment by travist** [comment] 2019-08-06 14:46
We will take a look.

**Comment by travist** [comment] 2019-08-07 15:00
Can you provide a JSFiddle showing the issue? Our QA department is looking to reproduce the issue and get it on our dev list.

**Comment by huzech** [comment] 2019-08-08 02:28
You can try this by click button ok in different pages. Textfield on page 2 is required. Only page2 and last alert('false').
https://jsfiddle.net/z3vjn702/

**Comment by jhen1422** [comment] 2019-08-09 13:32
@huzech 
Thank you for the report.
We have added this item to our backlog and will discuss priority in our weekly planning meeting next week. If you would like to expedite this issue, please email support@form.io for cost information.

Thank you!

**Closed** 2019-08-13 01:34 UTC
