### ISSUE TITLE
[BUG] DateTime component display format returns an incorrect date

### ISSUE THREAD

**Issue by fredxinfan** [formio/formio.js#4916] opened 2022-10-26 04:08 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.14.9
- Frontend framework:
- Browser: Chrome
- Browser version: 106.0.5249.119 (Official Build) (arm64)

## Steps to Reproduce
1. Create **DateTime** component in a **Wizard** form, change **Display** -> **Format** to `dd/MM/yyyy`.
2. Render the form in a browser with formio.js, select a date and click elsewhere to lose focus on the date field.

## Expected behavior
It should display the selected date in correct format, e.g. `26/10/2022`.

## Observed behavior
It changes the selected date to another date after losing focus, e.g. changes `26/10/2022` to `20/02/2022`.

It's only working correctly for the default format (`yyyy-MM-dd`).

The behavior doesn't appear in FormBuilder and FormManager, only happens to formio.js rendered forms.

## Example

https://user-images.githubusercontent.com/18909/197931875-097dc853-0781-4890-87a3-449e8be2cb31.mov

**Comment by nazmul-prince** [comment] 2022-10-31 17:12
@fredxinfan did you find the solution for this?

**Comment by arafatahmedtanimcsedu57** [comment] 2022-10-31 17:55
I am facing the same issue

**Comment by fredxinfan** [comment] 2022-11-01 02:39
@nazmul-prince @arafatahmedtanimcsedu57 A temporary solution that works for me is to downgrade to v4.14.8.

**Comment by dp-05** [comment] 2022-11-04 16:51
We're facing the same issue as well, except our date value clears completely when focus is clicked away from the date/time component input, using "dd/MM/yyyy" formatting. This only occurs when we set the field to required.

**Comment by Stewart-Fleming** [comment] 2022-11-08 06:11
> @nazmul-prince @arafatahmedtanimcsedu57 A temporary solution that works for me is to downgrade to v4.14.8.

Forgive the simple question but we include the formio.full.min.js in our solution. Is there are way to include the older version?

**Comment by fredxinfan** [comment] 2022-11-13 04:39
@Stewart-Fleming Go to https://www.jsdelivr.com/package/npm/formiojs?path=dist, and pick a version from the dropdown list on your right hand side and select the JS file link from the list, e.g.
https://cdn.jsdelivr.net/npm/formiojs@4.14.8/dist/formio.form.min.js
https://cdn.jsdelivr.net/npm/formiojs@4.14.8/dist/formio.form.min.css

**Comment by vgrover1** [comment] 2023-08-02 19:09
Do we have a fix for this yet ? or is there a workaround ???

**Comment by nazmul-prince** [comment] 2023-08-03 03:40
> Do we have a fix for this yet ? or is there a workaround ??? 
> I see the same problem even on Chrome's latest version

We have to downgrade to the lower version

**Comment by olgabann** [comment] 2024-04-03 11:26
@fredxinfan 

https://github.com/formio/formio.js/assets/128126697/b1618030-755b-4512-a64a-ae3a7ae12545

I could not reproduce the issue in formiojs@4.19.0. Please let us know if it persists.

**Comment by rjrjswrdvi** [comment] 2024-05-04 08:59
I am using Form io with Angular and having the same issue. Is there is any fix on the way?

**Comment by Sidiro23** [comment] 2024-09-04 13:27
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.

**Closed by Sidiro23** 2024-09-04 13:27 UTC
Labels: bug
