### ISSUE TITLE
[BUG] Conditionals Not Respected When Filling Out Form

### ISSUE THREAD

**Issue by crivera305** [formio/formio.js#3335] opened 2020-10-06 03:03 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.12.0
- Frontend framework: Bootstrap
- Browser: Chrome
- Browser version: 85.0.4183.121

## Steps to Reproduce
1.  Goto https://jsfiddle.net/mr24hour/jwbs2gh1/
2. Click on the checkbox for Contractor holds a State License
3. Panel "Professional Licenses" is shown
4. Type anything into field License #:
5. Notice panel disappears

## Expected behavior
1. Click on the checkbox for Contractor holds a State License
2. Panel "Professional Licenses" is shown
3. Type anything into field License # 
4. I should be allowed to continue to fill out the rest of the panel - it should not disappear

## Observed behavior
1. Click on the checkbox for Contractor holds a State License
2. Panel "Professional Licenses" is shown
3. As soon as i Type anything into field License # 
4. the whole panel disappears - disobeying the conditional rules

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

On load - https://prnt.sc/utt2q5
Select checkbox - https://prnt.sc/utt2so
When i type in license - https://prnt.sc/utt2uk

For code or form JSON, please enclose in a code block:

For the form please pull it from the script area of - https://jsfiddle.net/mr24hour/jwbs2gh1/

its a large form.

**Comment by wag110894** [comment] 2020-10-06 20:24
Hello @crivera305,

Thanks for reaching out and for providing alot of helpful information for us to investigate this issue. 

Taking a look at your code I saw that you had an API key that was duplicated. One of them was the Data Grid component &nbsp; which is located inside the Level II Background Check page. I changed the API key of that component and the Professional Licenses panel does not disappear anymore.

Here is a video of the issue is resolved using your form on our Sandbox as well as on the JSFiddle that you provided.
https://share.getcloudapp.com/o0umQLAZ

Once you make that change, then you should be good to go.

Have a great day!

**Comment by Tatsiana8** [comment] 2024-02-14 14:24
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by Tatsiana8** 2024-02-14 14:24 UTC
Labels: bug
