### ISSUE TITLE
Item template changes for select component whenever the control is open in edit mode in builder [BUG] 

### ISSUE THREAD

**Issue by pardeep224** [formio/formio.js#1802] opened 2019-10-03 13:24 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Local deployment
    - Version: 4.2.6
- Formio.js version: 4.2.6
- Frontend framework: angular-formio
- Browser: Google Chrome
- Browser version: 77.0.3865.90 (Official Build) (64-bit)

## Steps to Reproduce
1.  Take a select component on form.
2.  Set URL and set the field name in value property "param_id" and set item template value as "<span>{{ item.param_name }}</span>".
3.  click on save button.
4. Change any value of select component from UI.

## Example
NA
![Select1](https://user-images.githubusercontent.com/56104907/66130246-0720d180-e60f-11e9-9e3c-5f170213dd83.png)
![Select2](https://user-images.githubusercontent.com/56104907/66130251-0ab45880-e60f-11e9-9622-1e41e8c5319d.png)

**Comment by randallknutson** [comment] 2019-10-03 14:42
This is a known item that we are trying to resolve. We have had a lot of people report it but haven't been able to reproduce it yet for some reason. Can you provide a form or more information on how to reproduce it?

**Comment by sanjaykrgaur** [comment] 2019-10-14 05:33
This is happening due to the below code in select.edit.data.js

onChange: function onChange(context) {
    var valueProp = context.instance.data.valueProperty;
    var templateProp = valueProp ? valueProp : 'data';
    var template = "<span>{{ item.".concat(templateProp, " }}</span>");
    var searchField = valueProp ? "".concat(valueProp, "__regex") : '';
    context.instance.root.getComponent('template').setValue(template);
    context.instance.root.getComponent('searchField').setValue(searchField);
  }

template value is set to valueProp if it is present

**Comment by jhen1422** [comment] 2019-10-21 16:21
@sanjaykrgaur This should be resolved in v 4.4.2

**Closed by jhen1422** 2019-10-21 16:21 UTC
Labels: bug
