### ISSUE TITLE
[Bug] Tabs Component: issue with validation 

### ISSUE THREAD

**Issue by Aiso786** [formio/formio.js#869] opened 2018-12-17 09:57 UTC
Hello guys,

As you can see on this [JSFiddle](http://jsfiddle.net/v38du9y1/1145/), i have 2 tabs. The second one has a required field. I don't fill this required field, i leave it blank.
- If i submit the form while being on the second tab --> i can't submit, so it's **ok**.
- If i submit the form while being on the first tab --> the form is submitted, it's a **bug**.

Can you please help ?

**Comment by Aiso786** [comment] 2018-12-20 15:32
This is a serious issue, please help.

**Comment by travist** [comment] 2018-12-20 15:48
We will add this to our development backlog for next week.

**Comment by Aiso786** [comment] 2018-12-20 15:51
Thank you @travist

**Comment by jhen1422** [comment] 2018-12-20 17:06
@Aiso786 We have tested this issue on the latest version of formio.js.

Validation is working correctly https://jsfiddle.net/78t1mzjx/ .

Could you verify you are using the latest version of formio.js v3.10.0?

**Comment by Aiso786** [comment] 2019-01-09 16:19
Hello guys, any news ?

**Comment by travist** [comment] 2019-01-10 15:58
We have not been able to get to this yet. If you need this fixed very soon, there is an option to pay us to expedite the fix. Please reach out to support@form.io if you want to go down that route.

**Comment by Lastik** [comment] 2019-01-24 23:50
Hello, faced the same issue as well. Not a crucial one for us. Just pointing out that @Aiso786 is not the only one awaiting for the fix.

**Comment by mrcportillo** [comment] 2019-02-21 17:52
Hi guys, any news about this issue?

**Comment by Claudiomerli** [comment] 2019-02-22 08:29
Hi, we seriously need this bug fixed... Any news?

**Comment by wag110894** [comment] 2019-02-22 15:42
Hello All,

As noted by Travis, this is on a developer list to be done. If you need this fixed very soon, there is an option to pay us to expedite the fix. Please reach out to [support@form.io](mailto:support@form.io) if you want to go down that route. We will gladly accept a pull request if someone would like to fix it.

Thanks,
William Gay
Developer Support

**Comment by Lastik** [comment] 2019-02-22 18:55
Hi, William! Thx for your clarification. And thx for all of you for making such an amazing product! It's not about rushing ;) . I guess, me and other guys were just willing to find out the current status of the issue in your roadmap (not just 'done', 'to be done someday') :). As I understand, some misunderstanding happened because of @travist message, he told that it will be included to backlog for the next week. And I guess you have underestimated the complexity of the issue. But it is not clear from your message whether the issue is currently in progress, will be in progress in a month or maybe will be implemented only by some enthusiast via pull request. Task priority is one more useful attribute, which could be used by customers, and I think everyone would really appreciate if you could include it to your responses to future questions similar to this one. By the way is it possible for your team to publish some updatable roadmaps to prevent some of the annoying questions like this (e.g this spring: tasks list, features list; next sprint: tasks list, features list)?

For the others awaiting for the issue resolution. @Claudiomerli @mrcportillo @Aiso786 you cold try rolling back to angular-formio version 3.5.0, or to formiojs version 3.6.13 (if you are using pure non-angular one). This version is free of this bug. Good luck!

**Comment by travist** [comment] 2019-02-23 21:46
So we did determine based on how many people are needing this resolved that this was a high priority item for us to fix. Here is the commit that should resolve this problem.

https://github.com/formio/formio.js/commit/4d91601239820ea563f27748f78513aa5779f4ae

This will be in the **3.16.0** build.

**Closed by travist** 2019-02-23 21:46 UTC

**Comment by Claudiomerli** [comment] 2019-02-26 13:31
Thank you!

**Comment by Aiso786** [comment] 2019-02-26 14:26
Thank you very much guys.

**Comment by rended** [comment] 2019-04-01 08:59
cmon guys, i'm v3.18.3 and still have same error!!!

**Comment by rended** [comment] 2019-04-01 08:59
inap

**Comment by bohan** [comment] 2019-06-20 12:12
@rended https://github.com/formio/formio.js/issues/1249
And here's a [gist](https://gist.github.com/bohan/8e232851f13853ba5932f1a1247cfb3a) of the Tabs.js version that works.

**Comment by travist** [comment] 2019-06-20 14:46
@rended 

> cmon guys, i'm v3.18.3 and still have same error!!!

I am not sure if you noticed, but this whole project is Open Source, so fixing these types of things is a community effort. Please feel free to roll up your sleeves and debug the problem. We also provide support packages for those who need issues like this expedited to meet their project deadlines. We are here to help, but also depend on community effort to keep things moving and civil.
