### ISSUE TITLE
[BUG] Select components values aren't disabled if the component is within a panel

### ISSUE THREAD

**Issue by sutauma** [formio/formio.js#2696] opened 2020-04-22 11:58 UTC
## Environment
Please provide as many details as you can:

Hosting type
  Form.io
  Local deployment
Version: latest
Formio.js version: latest
Frontend framework: next.form.io
Browser: Safari, Firefox
Browser version: latest

## Steps to Reproduce
1. Create a panel 
2. Put a select component into the panel
3. Open the form and scroll the content so that the select component is nearly to the end of the browser window

## Expected behavior
The select component opens the value above the component and all values are consumable
## Observed behavior
The select component opens the values above the component and cuts nearly all values
## Example
![Weitere Risiken Spartenauswahl](https://user-images.githubusercontent.com/56014788/79979139-54786980-84a1-11ea-9510-fc4833bbe1f6.PNG)

**Comment by wag110894** [comment] 2020-04-22 14:35
Can you provide a form embed of this form so that we can replicate this issue?

**Comment by sutauma** [comment] 2020-07-13 11:25
```
{"_id":"5f057bf0556dac422497d2e0","type":"form","tags":[],"owner":"5d1b17f4293b9b5a1aefef8d","components":[{"label":"Checkbox","tableView":false,"key":"checkbox","type":"checkbox","input":true,"defaultValue":false},{"label":"Data Grid","reorder":false,"addAnotherPosition":"bottom","defaultOpen":false,"layoutFixed":false,"enableRowGroups":false,"tableView":false,"defaultValue":[{}],"key":"dataGrid","type":"datagrid","input":true,"components":[{"label":"Text Field","tableView":true,"key":"textField","type":"textfield","input":true},{"label":"Number","mask":false,"spellcheck":true,"tableView":false,"delimiter":false,"requireDecimal":false,"inputFormat":"plain","key":"number","type":"number","input":true},{"label":"Date / Time","tableView":false,"enableMinDateInput":false,"datePicker":{"disableWeekends":false,"disableWeekdays":false},"enableMaxDateInput":false,"clearOnHide":false,"key":"dateTime","type":"datetime","input":true,"widget":{"type":"calendar","displayInTimezone":"viewer","language":"en","useLocaleSettings":false,"allowInput":true,"mode":"single","enableTime":true,"noCalendar":false,"format":"yyyy-MM-dd hh:mm a","hourIncrement":1,"minuteIncrement":1,"time_24hr":false,"minDate":null,"disableWeekends":false,"disableWeekdays":false,"maxDate":null}},{"label":"Text Field","tableView":true,"key":"textField1","type":"textfield","input":true}]},{"label":"Edit Grid","tableView":false,"rowDrafts":false,"key":"editGrid","type":"editgrid","input":true,"components":[]},{"label":"Table","cellAlignment":"left","tableView":false,"key":"table","type":"table","numCols":1,"input":false,"rows":[[{"components":[{"collapsible":false,"tableView":false,"key":"panel","type":"panel","label":"Panel","input":false,"components":[{"label":"Select","widget":"choicesjs","tableView":true,"data":{"values":[{"label":"Value1","value":"value1"},{"label":"Value2","value":"value2"},{"label":"Value3","value":"value3"},{"label":"Value4","value":"value4"},{"label":"Value5","value":"value5"}]},"selectThreshold":0.3,"key":"select1","type":"select","indexeddb":{"filter":{}},"input":true}]}]}],[{"components":[]}],[{"components":[]}]]},{"type":"button","label":"Submit","key":"submit","disableOnInvalid":true,"input":true,"tableView":false}],"revisions":"","_vid":0,"title":"edit grid default","display":"form","access":[{"roles":["5ea2a956bde0eb606e0eead0","5ea2a956bde0eb7ed90eead1","5ea2a956bde0eb1c5e0eead2"],"type":"read_all"}],"submissionAccess":[],"controller":"","properties":{},"settings":{},"name":"editgriddefault","path":"editgriddefault","project":"5ea2a956bde0eb34190eeacf","created":"2020-07-08T07:55:28.463Z","modified":"2020-07-13T11:24:07.450Z","machineName":"nbqzeyclzsguduf:editgriddefault"}
```

**Comment by wag110894** [comment] 2020-07-13 15:36
Hello @sutauma,

Thank you for providing the json of this form as well as provide what you thought was the root cause of the issue. We are able to replicate this issue on our side and have added this to our backlog (FJS-1063). We welcome a PR and have a process to expedite if you are interested. Please contact support@form.io if you are interested in more information in expediting this issue. 

We will let you know once this issue has been resolved.

Thank you.

**Comment by jhen1422** [comment] 2020-09-23 18:17
@sutauma 
Should be resolved in formio.js version 4.12.0-rc11 >

**Closed by jhen1422** 2020-09-23 18:17 UTC
Labels: bug
