### ISSUE TITLE
[BUG] Performance degradation on Wizard form following upgrade from 3.22 to 4.8.1

### ISSUE THREAD

**Issue by ababic** [formio/formio.js#2531] opened 2020-03-13 17:00 UTC
Hi folks,

First of all, let me just start by saying what champs you for open sourcing this library, and thank you for the blood, sweat and tears that you have clearly put into it! It might be that there aren't resources available to investigate this fully without sponsorship, and that's quite okay. I thought it was important enough to raise so that there is some record, and in case others had experienced similar issues. This is kinda related to #1070, but is different in it applies to a quite recent version.

As the subject suggests, we recently upgraded an app to version 4.8.1 from 3.22 (also upgrading bootstrap from 3 to 4 the process). We have this one form, which is a multi-page wizard which makes extensive use of `TableComponent` with about 20ish rows in each, and has quite a bit of conditional field validation, and fields who's values are calculated from the values of other fields. We're noticing that general performance of this form is quite a bit worse after the upgrade (keypresses within number fields are slow to respond, and tabbing between fields also seems to lag quite a bit). The effect seems to worsen in correlation with the number of pages that are active (based on an answer given on the first page, 4-9 additional pages are toggled).

As one might expect, performance is worse in IE11 than elsewhere, where we're seeing multi-second delays between key presses. And when tabbing between fields in IE, the cursor regularly ends up in the URL bar due to the DOM not being responsive enough. Things are a little laggy in Chrome, Firefox and Edge too, but not so much that things are unusable.

In the app proper, we have some custom JS in the mix, which we wanted to rule out as the cause of this behaviour, so we have created some basic HTML pages that load the same form definition with the different versions of formio.js (plus the bare essentials). Please do let me know if you'd like a copy of these files to help with your debugging / benchmarking, and I'll happily share a ZIP with you so that you can reproduce locally.

It's hard to say for sure, but it appears that in 4.8.1, every change to a field now triggers validation to fields on all active pages instead of just on the fields from the current page (which looks to be the case in 3.22). Specifically, we're seeing lots of calls to `checkValidity()`.

Please let me know if you'd like any further information in relation to this. JS isn't my primary language, but I'll try to help where I can with reviewing any related PRs etc / doing some manual testing.

**Comment by randallknutson** [comment] 2020-03-13 20:40
Thanks for the encouragement!

We did significantly change the way things work between 3.x and 4.x, specifically around how components are instantiated in relation visible pages. Previously in 3.x we only instantiated components that were visible on the page but this caused all sorts of problems around components getting the wrong state when they did become visible and checking to see if the whole wizard was valid since you'd have to re-instantiate each page to check. To get around this we are now instantiating all components regardless of if they are visible or not and then only rendering and attaching components that are visible. This has generally worked out really well and in many cases has resulted in better performance than previously. However, there are still a few edge cases where it slows things down. This can happen when using a lot of custom logic on very large forms which may be what is happening here.

This may be a bit tricky to track down and we may either need to set up a support contract or have you do some of the investigation. The first place to look is in your browser's performance tab in developer tools. If you record long enough to do a keystroke it will report back what functions were called and what was taking a long time. If you can find that information it will help us know exactly what is causing things to run slower.

**Comment by ababic** [comment] 2020-03-16 09:42
> This may be a bit tricky to track down and we may either need to set up a support contract or have you do some of the investigation

Okay, we've floated the idea of a support contract with the client. We'll have to see what their procurement team says. In the meantime, let me know where I can send the necessary files for recreating this locally, and I'll email them over.

> The first place to look is in your browser's performance tab in developer tools. If you record long enough to do a keystroke it will report back what functions were called and what was taking a long time

The findings in my initial post are really a summary of what we've learned already from the performance tab. It's gotten to the point we know that, if there is a fix, it would have to be made in form.io itself, and would definitely require your expertise.

 Thanks again, and keep up the excellent work :)

**Comment by randallknutson** [comment] 2020-03-16 14:43
If you contact support@form.io we can see if something can be worked out. At the very least you can send the files there so we can investigate the issue. Thanks for reporting this! We are always interested in fixing regression, including performance, from previous versions.

**Comment by jeriah-formio** [comment] 2024-01-24 18:14
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by jeriah-formio** 2024-01-24 18:14 UTC
