### ISSUE TITLE
[BUG] Data input currency is broken 

### ISSUE THREAD

**Issue by sutauma** [formio/formio.js#2841] opened 2020-05-26 11:41 UTC
## Environment
Please provide as many details as you can:
Hosting type
  Form.io
  Local deployment
Version: latest
Formio.js version: latest
Frontend framework: next.form.io
Browser: Safari, Firefox
Browser version: latest

## Steps to Reproduce
1. Create a currency field with a default value e.g. 0
2. Open the form and click with the cursor on the field
3. Start typing your number (e.g. 10)

## Expected behavior
* The currency field shows 10,00 $

## Observed behavior
* Nothing happens

**Comment by wag110894** [comment] 2020-05-26 14:09
@sutauma Can you provide a JSfiddle of this issue occurring?

**Comment by sutauma** [comment] 2020-05-28 12:15
Hi,

https://jsfiddle.net/sutauma/uohw398q/2/

Proposal for a workaround:
The field content gets marked after clicking into the field.

**Comment by wag110894** [comment] 2020-05-28 14:34
@sutauma Thank you for providing the JSFiddle as well as a workaround. We are not able to replicate this issue on our side using the JSFiddle on either Safari or Firefox. Can you provide a screenshot of the issue occurring?

**Comment by airarrazaval** [comment] 2020-06-05 03:14
I think I get what is happening.  When you click on the input and the cursor is at the end, because the value is 0, when you type nothing will be inserted.

![image](https://user-images.githubusercontent.com/9391489/83831290-10d66980-a6b5-11ea-9143-e26a98f6d70e.png)

This happens because a number such as 01 is not a valid number. Now, if you click at the start of the input, you will be able to insert numbers without problem:

![image](https://user-images.githubusercontent.com/9391489/83831361-3f544480-a6b5-11ea-82f1-0f944979bf16.png)

I think this is the expected behavior (as to avoid an invalid number). Maybe a possible "fix" could be to attach a function on the `focus` event that would select the value if this is 0 so when you type you will replace the value with whatever digit you write.  You could have something like this running on your application:

```js
// Select all input DOM elements of all currency components in the form
document.querySelectorAll('.formio-component-currency input').forEach((input) => {
  // For each DOM element, add an event listener for the "focus" event
  input.addEventListener('focus', (e) => {
    // If the input's numeric value is "0"...
    if (e.target.value && e.target.value.replace(/\D/g,'') === '0') {
      // ...automatically select all of the text so that it can be overwritten on user type
      e.target.setSelectionRange(0, e.target.value.length);
    }
  })
});
```

Sources:

[Selecting all text in HTML text input when clicked](https://stackoverflow.com/questions/4067469/selecting-all-text-in-html-text-input-when-clicked)

**Comment by VikkiAlenn** [comment] 2024-01-31 14:49
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed** 2024-01-31 14:49 UTC
Labels: bug
