### ISSUE TITLE
File component support.

### ISSUE THREAD

**Issue by hauter** [formio/formio.js#105] opened 2017-06-07 09:27 UTC
Why doesn't it support for file component?

**Comment by coronoz** [comment] 2017-06-07 12:38
I have the same question, it seems that this library does not support file component, just throws the message "unknown component: file" when trying to render a file type input.

**Comment by rmckeel** [comment] 2017-06-13 16:33
I just hit on this limitation as well.  In my initial tests, I thought it would support, but it appears that that was because I had a wrapper of ngFormio or ng2-formio, which has file component support.

@travist Is this by design that formio.js does not allow the file component (even with the 'custom URL' designation)?  And if so, do you have a recommendation on how to bring in the 'official' file uploader, or perhaps a third party one such as FineUploader, into formio.js?

Thanks!

**Comment by rmckeel** [comment] 2017-06-14 23:27
For what it's worth (for me, hours of investigation and trial environment set up perhaps someone else can be spared), it appears ng2-formio doesn't have the file component either (just a pass-through to formiojs), whereas the ngFormio library does have the file component.

@travist I'm curious, is that a "to be done" or a "won't be done" for the file component in ng2-formio and/or formio.js?

Thanks!

**Comment by travist** [comment] 2017-06-23 17:34
This is now released in version 2.10.0. Thanks everyone for your patience and thanks @randallknutson for getting it done.

**Closed by travist** 2017-06-23 17:34 UTC

**Comment by rmckeel** [comment] 2017-06-23 19:22
Go @travist @randallknutson!  Thanks.

Does this mean NG2/4 apps will now have access to the file uploader as well?  And presumably, nothing will change for the NG1 app?

**Comment by coronoz** [comment] 2017-06-23 19:53
Thanks @travist and @randallknutson!!!!
