### ISSUE TITLE
Safari (formio.js >= 4.16.x): Columns component inside a Data Grid, the Columns are too narrow (unusable)

### ISSUE THREAD

**Issue by bobslee** [formio/formio.js#5426] opened 2023-12-06 21:18 UTC
### Observed behavior

**Browser**
- The issue (below) occurs in the **Safari browser** (version 16.6).
- Issue doesn't occur in recent Firefox, Chrome.

**Affected formio.js versions**
- 4.14.x => Not affected (no issue)
- 4.15.x => Affected (has issue)
- 4.16.x => Affected (has issue)
- 4.17.x => Affected (has issue)
- 4.18.x => Affected (has issue)

**Issue**
See the screenshots below.
A Columns component inside a Data Grid: The Columns are too narrow (unusable).

I also tested with Bootstrap versions: 4.1.3, 4.4.1, 4.6.2
No differences with the formio.js versions above; has the same outcome.

#### Form: Data Grid with Columns inside

<img width="943" alt="image" src="https://github.com/formio/formio.js/assets/328803/d363ecd4-579a-42ef-9e69-d38478d5a3d5">

#### Form Builder: Columns component

Some "Column Properties" are too narrow.

<img width="908" alt="image" src="https://github.com/formio/formio.js/assets/328803/c8bae9f3-4b61-4bf0-ad5d-442fa6c259cb">

**Comment by brendanbond** [comment] 2023-12-08 14:12
Hey @bobslee thanks for reporting this. I'm unable to reproduce this on the [form.io sandbox](https://formio.github.io/formio.js/app/sandbox.html); that being said, I'll make sure this gets in front of the folks that prioritize these tickets, if I had to guess it's likely a CSS issue in the @formio/bootstrap repo.

**Comment by bobslee** [comment] 2023-12-08 14:19
@brendanbond Thanks for answering and follow up.
Yes indeed it seems a bootstrap CSS issue or missing markup in the Columns component template(s).

**Concerning 1st screenshot (a form):**
In the form I did a workaround by either:
- Add `class=cols-md-X` to the other `<div>`s.
- A `width: 100%` could also help.

**Concerning 2nd screenshot (form builder component):**
I didn't checked the "Columns Properties" (also a columns component) in the Columns component tab.

Thanks!

**Comment by lane-formio** [comment] 2024-08-26 19:48
I'm gonna go ahead and close this as it looks all be resolved in the 5.x version of formio.js. We've also added a "Hide Preview" button in the editor to improve the UX when editing components that have columns.

**Comment by lane-formio** [comment] 2024-08-26 19:49
<div>Agent Lane Doughtie linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/48272">48272</a> for this issue.</div><br/>

**Closed by lane-formio** 2024-08-26 19:48 UTC
