### ISSUE TITLE
TextArea and TextField Default Values not available when Conditional Logic in place - Still issue exists

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#3135] opened 2020-08-12 10:28 UTC
Hi,

I am still able to see this issue with formiojs version **3.29.9**

Not working with below:
```json
{
    type: 'textarea',
    key: 'custom',
    label: 'Button Custom Logic',
    tooltip: 'The custom logic to evaluate when the button is clicked.',
    rows: 5,
    editor: 'ace',
    input: true,
    weight: 120,
    placeholder: "data['mykey'] = data['anotherKey'];",
    defaultValue: "data['mykey'] = 'testValue'",
    conditional: {
      json: { '===': [{ var: 'data.action' }, 'custom'] }
    }
  }
```

And working code:
```json
{
    type: 'textarea',
    key: 'custom',
    label: 'Button Custom Logic',
    tooltip: 'The custom logic to evaluate when the button is clicked.',
    rows: 5,
    editor: 'ace',
    input: true,
    weight: 120,
    placeholder: "data['mykey'] = data['anotherKey'];",
    defaultValue: "data['mykey'] = 'testValue'"
  }
```

Only difference is **conditional tag** not present in the working code.

I was checking in Changelog to see this issue fixed. I could see 3.22.6 version changes but after that no version till  3.29.16 has captured in changelog doc.

Is this an issue 3.29.x? 

_Originally posted by @sriram275 in https://github.com/formio/formio.js/issues/1278#issuecomment-672749547_

**Comment by wag110894** [comment] 2020-08-12 15:07
Hello @sriram275, have you tried using our 4x core renderer and see if the issue is resolved there? Our 4x core renderer provides a lot of great functionality as well as new components. 

Looking forward to your feedback. 

Thank you.

**Comment by VikkiAlenn** [comment] 2024-02-07 14:30
We're currently addressing a backlog of GitHub issues.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed** 2024-02-07 14:31 UTC
