### ISSUE TITLE
[BUG] day component setting required on day, month and year displays Default Value required on save form

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#2025] opened 2019-11-07 09:06 UTC
Formio 4.7.2 
In the builder if you use a Day component and make Day, Month and Year as required and try to save the form you get the following:

![Screenshot 2019-11-07 at 09 02 15](https://user-images.githubusercontent.com/290639/68374985-d831da00-013d-11ea-98b9-26708fd42cd1.png)

Not sure why it would need to do validation at this point. Even adding custom default value doesn't work.

**Comment by jhen1422** [comment] 2019-11-07 16:04
@aminmc 
Confirmed the issue. This seems to be isolated to the 4.7.2 version. Please revert back to an earlier version while we resolve this. 

Thanks!

**Comment by aminmc** [comment] 2019-11-07 17:05
I’m afraid I can’t revert to a lower version and there is an issue with Day component in the other version.

**Comment by travist** [comment] 2023-08-31 12:55
Just checked this on latest version and it seems to be working. Closing.

**Closed by travist** 2023-08-31 12:55 UTC
Labels: bug
