### ISSUE TITLE
Table has empty space

### ISSUE THREAD

**Issue by ghost** [formio/formio.js#3990] opened 2021-04-19 09:13 UTC
Hi,

![image](https://user-images.githubusercontent.com/58280615/115210899-3f243280-a129-11eb-82ee-d31c5756d874.png)

I have just upgraded the version of angular-formio from 4.11.4 to 4.12.0

I got an issue, the table has empty space.

**Comment by paulfalgout** [comment] 2021-04-19 13:41
This is likely a duplicate of https://github.com/formio/formio.js/issues/3986

**Comment by wag110894** [comment] 2021-06-23 15:58
This is how our table looks in builder mode. This will not appear that way on your form.

**Closed by wag110894** 2021-06-23 15:58 UTC
