### ISSUE TITLE
Formio date/time picker is returning one day of

### ISSUE THREAD

**Issue by usama967** [formio/formio.js#4897] opened 2022-10-11 19:32 UTC
I am using Form Io date/time picker but I unchecked the time component so that only the date will save on the database after unchecking the time's checkbox. It still sends the time along with the date in UTC like 2022-10-13T00:00:00+05:00 and while fetching the data from the server it converts it into the viewer's timezone like 2022-10-12T19:00:00.000Z.
Payload: 2022-10-13T00:00:00+05:00
Response: 2022-10-12T19:00:00.000Z 
Formiojs version: 4.14.7

**Comment by JubayerJoy** [comment] 2022-10-26 18:06
Hey @travist, our team is reporting this issue. Please let us know if this is added to formio dev backlog and if there is a way to track this.

**Comment by wag110894** [comment] 2022-10-26 21:22
@JubayerJoy can you provide a form embed of the issue taking place?

**Comment by JubayerJoy** [comment] 2022-11-02 20:07
Hey @wag110894, thank you for reaching out and apologies for the delay.

I have requested @usama967 to compose enough information to help you triage this. Our best guess is its happening due to an issue with flat picker date component.

**Comment by usama967** [comment] 2022-11-03 12:52
Hey @wag110894, Here is the link to the recorded video you can see the problem. Thanks 
[https://www.loom.com/share/87042493d28a4d41884569f1b5878deb](url)

**Comment by wag110894** [comment] 2022-11-03 21:34
Thanks for the video, what version of formio.js are you running?

**Comment by usama967** [comment] 2022-11-04 05:59
@wag110894 
Frontend: formiojs:  "4.14.7",
Backend: formiojs: "^4.15.0-rc.7",

**Comment by usama967** [comment] 2022-11-28 17:56
@magdacotoarba Unfortunately I didn't get any response. If I use moment = "2.29.3" and formiojs "4.14.7" will it be working fine?

**Comment by daneformio** [comment] 2024-02-07 14:15
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Comment by Hefaistos68** [comment] 2024-04-03 13:27
Should be fixed and not closed, this is definitely still relevant.

**Comment by daneformio** [comment] 2024-05-01 13:11
Are you able to reproduce this in the latest versions of the app? If so, can you provide an embed URL that our team can use to reproduce it?

**Comment by Hefaistos68** [comment] 2024-05-17 16:01
We are in the process of updating to the latest version, let's see.

**Comment by Sidiro23** [comment] 2024-09-04 13:23
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.

**Closed by Sidiro23** 2024-09-04 13:23 UTC
Labels: bug
