### ISSUE TITLE
[BUG] Uncaught TypeError: Cannot read property 'display' of undefined

### ISSUE THREAD

**Issue by samswbk** [formio/formio.js#1725] opened 2019-09-20 18:58 UTC
- Hosting type
  - [x] Form.io
  - [x] Local deployment
  - Version: branch master
- Browser: Google Chrome

Error:
Uncaught TypeError: Cannot read property 'display' of undefined
    at t.value (formio.full.min.js:19)
    at t (formio.full.min.js:19)
    at new t (formio.full.min.js:241)
    at l (formio.full.min.js:241)
    at Function.r.default.builder (formio.full.min.js:241)
    at window.onload (index.html:8)

Using the example code:
<html>
  <head>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://unpkg.com/formiojs@latest/dist/formio.full.min.css'>
    <script src='https://unpkg.com/formiojs@latest/dist/formio.full.min.js'></script>
    <script type='text/javascript'>
      window.onload = function() {
        Formio.builder(document.getElementById('builder'));
      };
    </script>
  </head>
  <body>
    <div id='builder'></div>
  </body>
</html>

**Comment by travist** [comment] 2019-09-20 20:47
duplicate of https://github.com/formio/formio.js/issues/1667

**Closed by travist** 2019-09-20 20:47 UTC
Labels: bug
