### ISSUE TITLE
[BUG] FormBuilder: misspelled option "isUseWorkerDisabled"

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#4164] opened 2021-06-23 11:58 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: n/a 
- Formio.js version: 4.13.2
- Frontend framework: react
- Browser: Google Chrome
- Browser version: Version 91.0.4472.114 (Official Build) (64-bit)

## Steps to Reproduce
1. Go to FomBuilder demo page: https://formio.github.io/formio.js/app/builder
2. Open Developer Console (F12)
3. Drag and drop a `Checkbox` control to the form
4. See the error in the console:
```
ace.js:1 misspelled option "isUseWorkerDisabled"
o   @   ace.js:1
setOption   @   ace.js:1
(anonymous) @   ace.js:1
setOptions  @   ace.js:1
eval    @   Component.js:2381
Promise.then (async)        
addAce  @   Component.js:2378
```

## Expected behavior
No error in the console

## Observed behavior
Error in the console

**Comment by upexcel** [comment] 2021-07-07 05:47
I am facing similar issue with angular.

"angular-formio": "^4.4.5",
"formiojs": "^4.13.2",

These issues are blocker - (Missing project Id and isUseWorkerDisabled).
My angular app slows down firefox because of these issues.

**Comment by airarrazaval** [comment] 2021-07-16 22:05
This is an issue caused by a custom setting used by form.io which is passed to the Ace Editor.  Checking the Ace Editor repo you can see that if an unknown key is passed to the editors. settings object, the warning message is displayed.

https://github.com/ajaxorg/ace/blob/94422a4a892495564c56089af85019a8f8f24673/lib/ace/lib/app_config.js#L74-L82

You can check form.io's implementation here:

https://github.com/formio/formio.js/blob/a56cc08744ece4f8c1e443c01a53d07475086192/src/components/_classes/component/Component.js#L2248-L2260

Created PR https://github.com/formio/formio.js/pull/4215 which fixes the warning message.

**Comment by olgabann** [comment] 2024-02-14 11:01
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by olgabann** 2024-02-14 11:01 UTC
Labels: bug

**Comment by ParhamShD** [comment] 2024-07-23 13:27
The issue is still present. Same steps and expected behavior as in the original ticket:
> ## Steps to Reproduce
> 1. Go to FomBuilder demo page: https://formio.github.io/formio.js/app/builder
> 2. Open Developer Console (F12)
> 3. Drag and drop a `Checkbox` control to the form
> 4. See the error in the console:
> 
> ```
> ace.js:1 misspelled option "isUseWorkerDisabled"
> o   @   ace.js:1
> setOption   @   ace.js:1
> (anonymous) @   ace.js:1
> setOptions  @   ace.js:1
> eval    @   Component.js:2381
> Promise.then (async)        
> addAce  @   Component.js:2378
> ```
> 
> ## Expected behavior
> No error in the console
> 
> ## Observed behavior
> Error in the console
