### ISSUE TITLE
why is each form element rendered 3 times per edit? [bug]

### ISSUE THREAD

**Issue by wating4321** [formio/formio.js#2163] opened 2019-12-09 11:34 UTC
when i edit the form ,each form element renderde 3 times at least,the httprequest will be visited 3 times at least too.

**Comment by aiwebb** [comment] 2019-12-09 15:34
@wating4321, do you have a JSFiddle or other example?

**Comment by wating4321** [comment] 2019-12-10 01:04
I can't give you an example for the moment, but I want to ask you whether this situation is normal and whether you have ever encountered similar situations

**Comment by wating4321** [comment] 2019-12-10 01:22
Another problem is that when the form is in edit state, I edit a component in the form that causes the entire form to be rendered again

**Comment by franke-mc** [comment] 2019-12-10 11:56
Recently I noticed the number of calls to custom JS code multiply, I guess it's the same as this issue.
Here's the JSFiddle: https://jsfiddle.net/franke_mc/tznoh3sk/66
The original issue #2067 of that fiddle is fixed now, but you can see that the custom JS is called many more times than it used to be (which was not caused by the fix to that issue, I think I tested that at the time of the fix).

**Comment by wating4321** [comment] 2019-12-10 12:13
So the problem is there, but how do I solve it

**Comment by franke-mc** [comment] 2019-12-10 14:33
Well, one approach would be to bisect to find out which commit introduced the problem... I'm pretty sure it was introduced only recently.

**Comment by wating4321** [comment] 2019-12-11 01:16
If this problem is solved, please inform me in time. Thank you very much

**Comment by wating4321** [comment] 2019-12-12 02:49
The version number of formiojs I used is 3.20.0. There is a function build in the base.js file of components, which will be entered 3 times every time when rendering a single form component. Is this a known problem? Now whether the latest version has solved this problem

**Comment by travist** [comment] 2019-12-12 15:21
Is this an issue with the latest 4.x release?

**Comment by franke-mc** [comment] 2019-12-12 17:08
Sorry for the confusion. I've split off #2183 for the issue I had thought would be the same as this one.

**Closed** 2024-01-24 14:50 UTC
