### ISSUE TITLE
[BUG] Select component weird behaviour

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1753] opened 2019-09-25 06:06 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.2.0-rc.7
- Frontend framework: react
- Browser:
- Browser version:

## Steps to Reproduce
1.  Create a form
2. Add select component
3. Attach external URL
4. Add value property e.g. id
5. Add label e.g item.test

## Expected behavior

Form should display label.

## Observed behavior
The drop down list displays the identifier instead of the label.  When you edit the form you see {{item.id}} instead of {{item.latest}}

This is causing massive problems for us as we don't expect this behaviour and when we update the component it reverts to this behaviour

**Comment by randallknutson** [comment] 2019-09-25 14:45
Hi Amin,

Can you provide an example form for this like a simplified use case? We did make some changes to the way the select component works since it had some bugs in it. We've had a couple of people report this which can happen when it searches the list of options for the value and can't find it. We need to look into why the option isn't being found.

It more than likely has to do with the Storage Type setting that was recently added which controls the typing of the stored value.

**Comment by aminmc** [comment] 2019-09-27 06:27
@randallknutson
Some steps:
1. Set label
2. If you change the datatype 
3. Save component preview
4. Edit component again
5.  Label changes

**Comment by jhen1422** [comment] 2019-09-27 14:46
@aminmc 
We're having trouble reproducing this on our end. When you reference the 'Label' are you referring to the Item Template or the value labels of the component? 

In my testing, changing the storage type does not change the item template. Here's a video of my testing https://www.screencast.com/t/z23OSUTCT

**Comment by aminmc** [comment] 2019-09-27 16:11
@jhen1422 here is a video of what I'm seeing:

http://somup.com/cqQtDQeHDL

You'll notice after I change type {{item.test}} changes to {{item.id}}

**Comment by jhen1422** [comment] 2019-09-27 21:15
@aminmc 
Thanks for the video.

We will have a dev investigate.

**Comment by randallknutson** [comment] 2019-10-01 13:20
This should fix the issue: https://github.com/formio/formio.js/pull/1783

**Comment by aminmc** [comment] 2019-10-01 13:36
I think this is a different issue that Travis might be looking at?

**Comment by travist** [comment] 2019-10-03 19:35
This will be included in the 4.2.12 release.

**Closed by travist** 2019-10-03 19:35 UTC
Labels: bug
