### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by baratdev** [formio/formio.js#2587] opened 2020-03-31 13:11 UTC
**this.component.rows[n].slice is not a function**

im getting this error in builder when i edit this form using custom builder, its may be some special character issue or something else and iam using your latest formio.full.min.js file then **builder.on('submit', (submission)** this function is not working but its working with old file.
So can anyone help me with these issues?

Here is the code Example
https://codepen.io/barat95/pen/BaNbKzX

**Comment by wag110894** [comment] 2020-03-31 13:41
@barat95 can you please provide a JSFiddle of this issue taking place?

**Comment by barat95** [comment] 2020-03-31 14:16
https://codepen.io/barat95/pen/BaNbKzX
Here you can check in console its showing error **this.component.rows[n].slice is not a function**
and also **builder.on('submit', (submission)** this is not working with the latest formio.full.min.js file.

**Comment by barat95** [comment] 2020-04-02 13:18
is there anyone who can help me with these issues?
Thanks in Advance
@travist @wag110894 @silbermm @cymen

**Comment by cymen** [comment] 2020-04-02 20:20
@barat95 I've found the quality of releases to be highly variable. I'd suggest trying different versions and then using only that version -- not latest. I'm using one version where a few things are broken but I've worked around those issues and would prefer to work with something that I know works for my use case instead of deal with other core things breaking that I am using (which I experienced when trying to use latest).

That said, reading your original question, it sounds like bad JSON for the form data. Maybe I'm wrong but you're going to want to share a reproducible breakage else people can't really help.

**Comment by barat95** [comment] 2020-04-03 04:52
In my project i was using 4.7.8 its working all fine with some issues but when i use formiojs v4.9.1
builder.on('submit', (submission) => 
            {console.log("herer");})
this on submit not working did you guys change any method with this in 4.9.x release?
I want to use this version(4.9.x) but due to this submit not working i have to you old version(4.7.8).
Any help?

**Comment by barat95** [comment] 2020-04-10 13:48
How to use File Types in File Component?
@travist

**Comment by VikkiAlenn** [comment] 2024-01-31 14:40
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed** 2024-01-31 14:40 UTC
Labels: bug
