### ISSUE TITLE
Custom (URL) File storage - delete unused files?

### ISSUE THREAD

**Issue by nathanieltagg** [formio/formio.js#2406] opened 2020-02-11 16:16 UTC
I'm using the file upload component to send files to my own storage.

I've noticed in testing that the file is sent immediately when the user does the drag-and-drop, not on submission of the form.   However, if the user clicks the 'x' button to remove the file, there is no corresponding call to the server to remove the unused file.

This may result in a lot of wasted storage, even if there is no foul play by users.  A user might rightfully think that nothing has been committed until the 'submit' button is pressed, but in fact the file is stored permanently.

Solution 1:
 - When the user clicks the 'x' to remove the file, the client sends a DELETE request with the file key to the server at the url
- When the user leaves the form page with form unsubmitted, same thing happens

Solution 2:
- When the form is submitted, the 'metadata' field in the submission key lists all used and file keys (or urls).   
    metadata : {
        fileKeysSubmitted: [ { storage: "url", url: "http://blah.com/files/file123.jpg", ...}, ...],
        ....}
The server can then log these as used keys, and once in a while clean out the unused cruft.

What do you think?

**Comment by randallknutson** [comment] 2020-02-11 21:23
We've had some work done around the first solution but I'm not sure it has been implemented for all storage providers. We'd love someone to add that as it does get requested from time to time.

We've also had a request for the server to do some cleanup when a submission is deleted and check for any files and delete them. This also is something we want but haven't resourced yet.

**Comment by nathanieltagg** [comment] 2020-02-14 17:50
There appears to be some inconsistency in the code. When the URL provider is chosen, the File class uses a Formio object as the FileService, which in turn impliments the url.js fileService. It does this for upload and downloadFile functions, but not deleteFile.

For reference, I can force Formio to actually do what it's supposed to with this snipped added postfacto:

```
Formio.prototype.deleteFile = function(fileinfo) {
  if(fileinfo.storage=="url" && fileinfo.url) {
    $.ajax({type: "DELETE",
            url: fileinfo.url,
            success: function(msg) { console.log("File deleted"); }
    });
  }
  console.log(fileinfo);
}
```

**Comment by travist** [comment] 2020-02-17 15:24
The problem is that this is very opinionated that the file URL even supports the DELETE method on that url. We probably should add this, but I believe this is the reason why we did not add this code. Go ahead and create a pull request with your suggested fix and we will review it on our end for contribution.

**Comment by nathanieltagg** [comment] 2020-02-17 21:06
I don't know how to build formio.js from source; I've been patching with code in the browser.  There are no instructions, and I don't really want to figure it out from inspection (as I've had to do with every other thing in this code library).

**Comment by randallknutson** [comment] 2020-02-17 21:33
If you are using any type of module bundler (like webpack or typescript) it is relatively easy to make changes to the formio.js library and test them out. 

As Travist mentioned, the reason we don't have something like this in the library already is that we have a lot of different storage providers and each one of them may or may not support a DELETE call and have different syntax. It is definitely something we are interested in adding but haven't had a chance to do it yet. We'd love a contribution to add it.

**Comment by mm-dsibinski** [comment] 2021-03-09 12:11
The haxy solution proposed by @nathanieltagg doesn't work anymore.
Is there any way to implement/inject custom code on file deletion with "X" button from the form?

**Comment by travist** [comment] 2021-03-09 15:11
The "deleteFile" method does go through our Plugin system.

https://github.com/formio/formio.js/blob/master/src/Formio.js#L601

It uses the "deleteFile" key. I would read how to create a plugin @ https://github.com/formio/formio.js/wiki/Fetch-Plugin-API and see if you can create a plugin that hooks into this "deleteFile" hook

**Comment by nathanieltagg** [comment] 2021-03-10 15:28
After I submitted the haxy solution, I realized problem IS fraught. For example, imagine you are editing a user profile, and there is a portrait of the user.  The user hits the 'x' button next to the picture, but does not commit the form.  Because they hit the 'x' button, it issued the DELETE command, but they hadn't actually committed to that action. 

If an 'undo' is ever implemented, same problem.

That's why I actually think this needs a more complete solution. There should be a way to queue file-deletions and only execute them if the form is committed.   Maybe that can all be done in userland?

**Comment by mm-dsibinski** [comment] 2021-03-11 04:22
Yes, I think the same @nathanieltagg 
I, for now, keep the current FormIO behavior and will implement some periodical files cleaning solution. With `jsonpath` it's easy to fetch all file names used in the `submission`s of the forms. I'm implementing a solution which fetches all these names present in `submission`s submitted by the users (and saved into the database) and removing all files not present in any `submission`.

I agree that a more complete solution for files management is needed here. It makes sense that all file operations are executed when the form is submitted.

**Comment by VikkiAlenn** [comment] 2024-01-31 14:28
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed** 2024-01-31 14:29 UTC
