### ISSUE TITLE
[BUG] Infinite onChange events with Resource select boxes in a nested form

### ISSUE THREAD

**Issue by darabi** [formio/formio.js#1652] opened 2019-09-10 12:52 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.0.0-rc.31 (via react-formio)
- Frontend framework: react-formio 4.0.0-rc.18
- Browser: Chrome + Firefox
- Browser version: Chrome 76.0.3809.100 Linux

## Steps to Reproduce

I am not able to create a small reproducible sample. I have a form with 3 nested forms; they have some Selects which reference Resources

In a simple case, everything works as expected, but in a more complex case, I have Webform.onChange being fired indefinitely.

## Expected behavior

A small number of onChange calls until everything has stabilised.

## Observed behavior

Infinite onChange calls.

**Comment by randallknutson** [comment] 2019-09-10 14:45
We've seen this happen if there are components have the same property name (key). Can you check if there are any duplicates that could be causing this?

**Comment by darabi** [comment] 2019-09-10 15:16
Thank you for your quick response.

I made sure all keys have a unique value but the behaviour remains the same.

**Comment by darabi** [comment] 2019-09-10 15:50
While debugging, I stumbled upon `NestedComponent.checkData` which looks like this:

```
  /**
   * A more performant way to check the conditions, calculations, and validity of
   * a submission once it has been changed.
   *
   * @param data
   * @param flags
   */
  checkData(data, flags, source) {
    flags = flags || {};
    let valid = true;
    if (flags.noCheck) {
      return;
    }

    // Update the value.
    let changed = this.updateValue(null, {
      noUpdateEvent: true
    }, source);

    // Iterate through all components and check conditions, and calculate values.
    this.getComponents().forEach((comp) => {
      if (comp.checkData) {
        valid &= comp.checkData(data, flags);
      }
      changed |= comp.calculateValue(data, {
        noUpdateEvent: true
      });
      comp.checkConditions(data);
      if (!flags.noValidate) {
        valid &= comp.checkValidity(data);
      }
    });

    // Trigger the change if the values changed.
    if (changed) {
      this.triggerChange(flags, changed);
    }

    // Return if the value is valid.
    return !!valid;
  }
```
If I interpret the code correctly, the lines

```
    // Update the value.
    let changed = this.updateValue(null, {
      noUpdateEvent: true
    }, source);
```
reset the value of the nested component completely to then iterate through the components, re-calculate the values and check the validity.

But, if this is true, then why is the initial result of `updateValue(null...)` used to decide upon triggering a change:

```
      if (changed) {
        this.triggerChange(flags, changed);
      } // Return if the value is valid.
```

This seems counter-intuitive to me, and in fact, the initial `updateValue(null..)` does return `true` in my case.

**Comment by travist** [comment] 2019-09-11 11:48
Will you try it with the changes in this pull request?  

https://github.com/formio/formio.js/pull/1660

Here we are refactoring the checkData method to be easier to understand and more performant, and it may be the case that it solves this problem.

**Comment by darabi** [comment] 2019-09-12 04:45
@travist: thank you for the PR #1660 which indeed solves the problem

**Comment by gcrofils** [comment] 2019-09-17 06:51
I saw also this error when a `select` component is inside a `columns` component. 
It somehow related to this issue since it looks like the builder duplicates the `select` component (once in  `columns` array field, once deeply embedded in `components` fields).

I fixed it setting the type of the select to `number`
Still not fixed with version v4.0.9

**Comment by jhen1422** [comment] 2019-09-17 15:03
@gcrofils Can you create a separate issue on your latest comment and provide an example please?

Thank you!

**Closed** 2019-09-17 15:04 UTC
Labels: bug

**Comment by gcrofils** [comment] 2019-09-19 16:04
@jhen1422 I can not reproduce it anymore. Looks like v4.1.0 fixed it. 
Thanks ! :-)
