### ISSUE TITLE
[BUG] Day Component does not respect "disabled" property on containers/layouts

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3279] opened 2020-09-20 19:40 UTC
If you set the Day component into a container and set the container to disabled the day component does not get disabled.

https://formio.github.io/formio.js/app/builder

```json
{
    "display": "form",
    "components": [
        {
            "label": "My Container",
            "hideLabel": false,
            "disabled": true,
            "tableView": false,
            "key": "myContainer",
            "type": "container",
            "input": true,
            "components": [
                {
                    "label": "Field 1",
                    "tableView": true,
                    "key": "field1",
                    "type": "textfield",
                    "input": true
                },
                {
                    "label": "Day",
                    "hideInputLabels": false,
                    "inputsLabelPosition": "top",
                    "useLocaleSettings": false,
                    "tableView": false,
                    "fields": {
                        "day": {
                            "hide": false
                        },
                        "month": {
                            "hide": false
                        },
                        "year": {
                            "hide": false
                        }
                    },
                    "key": "day",
                    "type": "day",
                    "input": true,
                    "defaultValue": "00/00/0000"
                }
            ]
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```

**Comment by StephenOTT** [comment] 2020-09-20 19:42
<img width="760" alt="Screen Shot 2020-09-20 at 3 41 10 PM" src="https://user-images.githubusercontent.com/1994838/93720542-bbd13d00-fb57-11ea-89e1-810c869861ec.png">


<img width="961" alt="Screen Shot 2020-09-20 at 3 41 55 PM" src="https://user-images.githubusercontent.com/1994838/93720558-d5728480-fb57-11ea-9b48-79d37c7bc7e6.png">

**Comment by mohlendo** [comment] 2020-09-21 07:44
Duplicate of #3256

**Closed** 2020-09-21 12:35 UTC
Labels: bug
