### ISSUE TITLE
v2.23.1 Breaks File component inside Datagrid

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#257] opened 2017-11-21 20:07 UTC
Today I updated the Library to v2.23.1 and all the Forms that had the File component inside a Datagrid stopped showing. Later downgraded back to v2.22.1 and everything works fine again.

The console doesn't display any error, so there is nothing that I could post over here to guide you on that. :(

**Comment by travist** [comment] 2017-11-21 22:19
Thanks for letting us know @cabrerabywaters .

We did find an issue with calculated values with the latest release so not sure if that may have caused it. Rolling a new version soon. Will you let us know if that fixes it?

If not, then please create a jsfiddle of this issue so we can reproduce and fix on our end.

Thanks.

**Comment by travist** [comment] 2017-11-21 22:21
It may have been caused by this commit. 

https://github.com/formio/formio.js/commit/418d8de7d767603388add86192d663bc48c7e383

@douglaselee could you verify?

**Comment by douglaselee** [comment] 2017-11-22 00:07
Sorry to hear that @travist.  Will investigate ASAP.

**Comment by douglaselee** [comment] 2017-11-22 02:06
Hi @travist,

I think you merged that commit on the 9th.  Randall bumped version to 2.22.0 on the 10th.  User reports things are working in 2.22.1.  Another change has been made to .../file.js since the 9th but I don't know if it's related to the problem.

**Comment by douglaselee** [comment] 2017-11-22 15:22
Hi @travist,

Tried with latest formio.js and entire grid containing file component is not rendered as user reports.  Removed code from suspected commit (add file limitations) and problem persists.  Also noted that subsequent change to .../file.js was on the 10th and so also probably in 2.22.1.

**Comment by cabrerabywaters** [comment] 2017-11-22 15:50
Hi @travist 
No problem, whenever you have the new version I can give it a try.

**Comment by douglaselee** [comment] 2017-11-22 16:07
Hi @cabrerabywaters,

The new version didn't help me solve your problem.  Doesn't seem related to calculated value script issue.

Hi @travist,

Also noted that form components following the file containing grid aren't rendered including the submit button.

**Comment by douglaselee** [comment] 2017-11-22 18:18
Hi @travist and @cabrerabywaters,

If I revert change to .../file.js from commit https://github.com/formio/formio.js/commit/4e242a491f0951e253b18ee193af7d62b668c4b6 the form renders and file component in grid works.

With that change I see:
DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at FileComponent.refreshDOM (http://localhost:3000/formiojs/formio.form.js:5980:22)
    at FileComponent.setValue (http://localhost:3000/formiojs/formio.form.js:5941:12)
    at http://localhost:3000/formiojs/formio.form.js:4811:18
    at arrayEach (http://localhost:3000/formiojs/formio.form.js:19358:9)
    at forEach (http://localhost:3000/formiojs/formio.form.js:24400:10)
    at http://localhost:3000/formiojs/formio.form.js:4803:28
    at arrayEach (http://localhost:3000/formiojs/formio.form.js:19358:9)
    at forEach (http://localhost:3000/formiojs/formio.form.js:24400:10)
    at DataGridComponent.buildRows (http://localhost:3000/formiojs/formio.form.js:4800:26)
    at DataGridComponent.buildTable (http://localhost:3000/formiojs/formio.form.js:4786:12)

**Comment by travist** [comment] 2017-11-23 01:37
@YuryRybakSoftensity will you please investigate? This seems to have been broken with your commit to add dynamic label positions.

**Comment by YuryRybakSoftensity** [comment] 2017-11-23 12:53
Should be fixed with https://github.com/formio/formio.js/pull/264

**Closed** 2017-11-25 16:40 UTC

**Comment by Mochaka** [comment] 2018-12-19 01:43
Sorry to bring up an old post, but i didn't want to open a new issue. I'm getting the same error as above

Got any suggestions on how to debug this?

Thanks

Uncaught (in promise) DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at http://localhost:8080/5.js:29415:40
(anonymous) @ File.js:831
Promise.catch (async)
(anonymous) @ File.js:824
upload @ File.js:755
onChange @ File.js:252
