### ISSUE TITLE
[BUG] Edit of control "Day" not saved in form builder

### ISSUE THREAD

**Issue by ssrini** [formio/formio.js#1421] opened 2019-06-26 12:19 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: Latest
- Formio.js version: Latest
- Frontend framework: JS
- Browser: Chrome
- Browser version: Latest

## Steps to Reproduce
1. Use the sample code in https://github.com/formio/formio.js to display the builder or the hosted demo at https://formio.github.io/formio.js/app/builder
2. Open Advanced and add a Day control.
3. In the popup under Validation, select Require Day and hit Save
4. The control is not added and no errors are displayed, popup stays on screen
5.  If you uncheck Required Day and add it works.  Now edit the field and select Require Day and it does not save again

## Expected behavior
1.  If Require Day (or other require fields are selected) the form element should be added in the builder

## Observed behavior
Popup stays open without saving the changes made

For code or form JSON, please enclose in a code block:

```js
// This is the sample code from the link https://github.com/formio/formio.js

<html>
  <head>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://unpkg.com/formiojs@latest/dist/formio.full.min.css'>
    <script src='https://unpkg.com/formiojs@latest/dist/formio.full.min.js'></script>
    <script type='text/javascript'>
      window.onload = function() {
        Formio.builder(document.getElementById('builder'));
      };
    </script>
  </head>
  <body>
    <div id='builder'></div>
  </body>
</html>
```

**Comment by ssrini** [comment] 2019-06-26 12:35
I can confirm that this works on form.io cloud with the free account also

**Comment by randallknutson** [comment] 2019-06-26 14:50
You have the formio.js version marked as "Latest" is that the latest stable (v3.22.9) or latest beta (v4.0.0-beta.53)?

**Comment by ssrini** [comment] 2019-06-26 18:01
3.22.9. Note that this also occurs in the formio demo

**Comment by randallknutson** [comment] 2019-06-26 20:48
We'll open a ticket to add this to our backlog. You can also submit a pull request if you find the issue yourself or you can contact support to expedite the issue to have it fixed faster.

**Comment by ssrini** [comment] 2019-06-27 02:01
Thanks Randall. Will look into this.

Out of curiosity, how does this work on the form.io cloud since the core is
probably the same?

**Comment by ssrini** [comment] 2019-06-27 09:27
The issue seems to be with the default value required when a part of Day/Month/Year is made required.  If no default value is entered then save is not permitted.  But if a default value is set then it saves

**Comment by randallknutson** [comment] 2019-06-27 14:47
Gotcha. The issue is that the default value field should remove the required validation but day has a special validation that must not be getting removed. 

This is the code where we remove the validations. https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L291-L298

We need to remove the day/month/year required settings as well.

**Comment by jhen1422** [comment] 2019-07-24 21:23
This issue has been resolved

**Closed by jhen1422** 2019-07-24 21:23 UTC
Labels: bug
