### ISSUE TITLE
Datetime component does not perform validation on value change[BUG] 

### ISSUE THREAD

**Issue by zymantasj** [formio/formio.js#1455] opened 2019-07-08 11:41 UTC
## Environment
- Hosting type
  - [x] Form.io
  - [ ] Local deployment
- Formio.js version: 3.23.0

## Steps to Reproduce
1. Create Datetime component
2.  Add custom validation
3. Open form and change date value

## Expected behavior
Custom validation is called after value  change
## Observed behavior
Custom validation  is not performed on value change. It is performed on only on form submission
## Example
https://jsfiddle.net/o1sp498m/ 
message should be printed in console when value is changed. Now it is only printed when a form is submitted.

**Comment by wag110894** [comment] 2019-07-08 16:20
Can you confirm that you have the 'Required'  checkbox checked?  This is located in the Validation Tab.

Hope this helps.

Thanks.

**Comment by zymantasj** [comment] 2019-07-08 19:10
I have tried it with 'Required' checkbox checked and unchecked.
Although I'm not quite sure how it should help. It only enables check if value is present and not enables/disables any validation. At least that's how it behaves in other components so I'd expect the same behavior in this component as well.

**Comment by airarrazaval** [comment] 2019-07-17 20:45
I can confirm this.  Only after you submit and trigger an error the component starts validating (most probably due to the fact of the error flag that forces the form to validate components).

**Comment by slv008** [comment] 2019-09-24 17:04
Does anyone has a fix for this issue? Happens for me too, on v3.25 . Thank you

**Comment by jhen1422** [comment] 2019-09-25 14:33
@slv008 This should be resolved on our latest renderer. Can you try the latest 4x version ?

**Comment by slv008** [comment] 2019-09-25 14:38
> @slv008 This should be resolved on our latest renderer. Can you try the latest 4x version ?

I started to modify the library and will continue to use the 3.25 version. In the meantime I managed to fix it by manually applying the fixes from here:

https://github.com/formio/formio.js/pull/1643/files

Thank you

**Comment by heather-formio** [comment] 2022-10-12 12:51
Closing this thread as it is stale. Please feel free to reopen if needed.

**Closed by heather-formio** 2022-10-12 12:51 UTC
Labels: bug
