### ISSUE TITLE
[BUG] checkValidity() not validating required fields.

### ISSUE THREAD

**Issue by rubandangol** [formio/formio.js#4617] opened 2022-02-25 12:21 UTC
checkValidity() isn't working anymore. We depend on this to manipulate data and validate it. It was working fine when I first implemented it a while back and I just realized that there are a bunch of invalid data going through because the checkValidity function has only been returning true for a while now. I am also calling the setPristine function before checkValidity. This is a massive issue, please help!!!

@formio/angular: 5.2.2
formiojs: 4.14.1

**Comment by sthammav** [comment] 2022-03-01 16:18
Saw the other issue reported before, https://github.com/formio/formio.js/issues/1352.  So, I've tried setPristine(false) before doing the checkValidity() as well.  Sometimes it works, sometimes it doesn't.  We need to be able to check the form manually before the user enters the form.  We've got required fields as well.  checkValidity() seems buggy so we can't rely on this method. Is there another alternative?

**Comment by rubandangol** [comment] 2022-03-07 02:31
@randallknutson  @travist , is this something you guys are aware of? And is there any alternative solution we can use to simply do a validation check without submitting the form?

**Comment by edwinanciani** [comment] 2022-03-07 22:09
Hi, @rubandangol @sthammav could you send any console errors screenshots or steps to reproduce this issue?

**Comment by sthammav** [comment] 2022-03-08 22:49
So I've tried using just the Javascript SDK + JSFiddle - https://jsfiddle.net/sthammav/y4r53Lzt/64/ .  On initial load, in the on form change event, if you don't type anything, the isValid flag is true.  Which seems wrong.  It should be false.  I haven't entered anything in the form yet.  So we couldn't rely on the on form change event.

So I was using the checkValidity() to manually check the form is valid on load (no user input yet).  I was trying to figure out an event to capture the manual check if the form is valid when you don't type anything on required field forms so I've put in the on blur event.  

In our code in ReactJS, if the state changes, this function checkValidity() works and sometimes doesn't work.  I can't seem to reproduce it though using the codesandbox.  So I'm still working on the code sample.

But for the issue above in the form on change event, we can't rely on the isValid flag.
![image](https://user-images.githubusercontent.com/15822738/157338796-88900797-32f9-4e64-9924-4a95d9df755a.png)

**Comment by edwinanciani** [comment] 2022-03-10 22:37
@sthammav could you try to setPristine to false and then redraw the form instance?
``` 
form.ready.then(() => {
  form.setPristine(false);
 console.log('Form is ready');
  form.redraw();
  });
```

**Comment by edwinanciani** [comment] 2022-03-11 22:23
@sthammav it seems there is a change event when the default values are triggered. I have tried this. But I still do not understand the use case for this implementation could you give me a little more information on that.
https://jsfiddle.net/edwinanciani/x1e9fjcq/

**Comment by sthammav** [comment] 2022-03-15 13:41
@edwinanciani The use case is that we want to keep track of the state of whether the user has filled out all the required fields in ReactJS before the user can continue to the next step we need capture data besides the formIO forms.  As you can tell, we aren't using the submit button.   So the onFormChange method, isValid flag is giving false state on the first form change event.  So we switch to using the checkValidity method.  And we've found out that method is buggy.  I'm not sure if it's a browser/Chrome issue or not. 

 @rubandangol Did you notice if the bug in checkValidity happened on certain browsers?  I've updated my Chrome browser and not able to reproduce it.

**Comment by edwinanciani** [comment] 2022-04-20 21:30
@sthammav And for this use case this code is not working for you?
```
form.ready.then(() => {
  form.setPristine(false);
 form.checkValidity();
  form.redraw();
  console.log('Form is ready');
  });
```

**Comment by xnandersson** [comment] 2022-04-21 15:35
Hi, representing a client that wants to see this issue fixed. I am assessing the options to do this the right way, before we do anything less optional:

1. Is this a regression? (The feature has worked in past versions, but no longer. I.e it is a "bug", and not a "feature request")
2. Is there a test framework that supports/confirms this?
3. Is there anybody currently working on this (so we don't duplicate efforts)
4. Anything I need to know with respect to sending pull requests and licensing? (Basically that the contributor doesn't need to sign a CLA - Contributor License Agreement)

Regards,
Niklas

**Comment by daneformio** [comment] 2024-02-07 14:35
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by daneformio** 2024-02-07 14:35 UTC
Labels: bug
