### ISSUE TITLE
[BUG] Submit button not disabled on wizard form

### ISSUE THREAD

**Issue by moeVdm** [formio/formio.js#2795] opened 2020-05-14 21:03 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: 4.9.9
- Frontend framework: using the javascript library
- Browser: Chrome
- Browser version: Version 81.0.4044.138 (Official Build) (64-bit)

## Steps to Reproduce
1. Create a form using the form renderer by providing a wizard form definition (not by url)
2. Submit the form

## Expected behavior
Submit button is disabled during submission

## Observed behavior
Submit button is not disabled

## Example
https://jsfiddle.net/g4820xr7/2/

The form renderer doesn't seem to work similarly when creating the form by url or by providing it a form definition for wizards.

In my example, I'm providing a wizard form definition without the buttons (previous, next, submit). The renderer is generating these buttons, but when submitting, the submit button is not disabled and I can't even seem to manually disable it by manipulating the DOM.

In your examples, using the form renderer with a url, the submit seems to work properly.

**Comment by randallknutson** [comment] 2020-05-15 15:04
The issue is that the form has nowhere to submit to so it just completes. You either need to load the form from a url or set the url option on the form. This will allow the form to submit to the url. If you don't want to do that you can also listen for the submit event and do whatever you want when they press the submit button.

**Comment by moeVdm** [comment] 2020-05-19 12:38
In my example, I am listening to the submit event and I am disabling the button, but I does not seem to disable it.

It feels like it is being disabled, but somewhere behind it is re-enabling right after.

**Comment by VikkiAlenn** [comment] 2024-01-31 14:47
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed** 2024-01-31 14:47 UTC
Labels: bug
