### ISSUE TITLE
[BUG] Design issue on small screen

### ISSUE THREAD

**Issue by rubandangol** [formio/formio.js#1628] opened 2019-09-04 12:59 UTC
Everything looks fine until you switch to a small screen. All the components placed within a column component tries to fit on the same line and everything looks messed up on small devices. I recently switched to bootstrap 4 from 3 and that's when I started facing this issue. Previously when using bootstrap 3. each component would fall to the next line and the design would look fine. I am using the latest stable versions of formiojs and angular-formio.

Here's how it looks right now.

![image](https://user-images.githubusercontent.com/15991812/64256866-ffa0d680-cf43-11e9-9476-8fb2434cff79.png)

**Comment by aiwebb** [comment] 2019-09-04 14:31
@rubandangol, can you provide some example form JSON?

**Comment by rubandangol** [comment] 2019-09-04 15:04
{"type":"form","tags":[],"owner":"59f91db89255f000010645c5","components":[{"customClass":"testclass","properties":{"":""},"conditional":{"show":"","when":null,"eq":""},"tags":[],"type":"well","tableView":false,"input":false,"key":"well","clearOnHide":false,"hideLabel":false,"components":[{"properties":{"":""},"conditional":{"show":"","when":null,"eq":""},"tags":[],"type":"columns","key":"wellColumns","tableView":false,"input":false,"clearOnHide":false,"hideLabel":false,"columns":[{"components":[{"labelPosition":"top","properties":{"":""},"tags":[],"type":"textfield","conditional":{"show":"","when":null,"eq":""},"validate":{"required":true,"minLength":0,"maxLength":50,"pattern":"","custom":"","customPrivate":false},"clearOnHide":false,"hidden":false,"persistent":true,"unique":false,"protected":false,"defaultValue":"","multiple":false,"suffix":"","prefix":"","placeholder":"","key":"firstName","label":"firstName","inputMask":"","inputType":"text","tableView":true,"input":true,"lockKey":true,"hideLabel":false,"autofocus":false,"spellcheck":true,"inputFormat":"plain"}],"width":4,"offset":0,"push":0,"pull":0},{"components":[{"properties":{"":""},"tags":[],"type":"textfield","conditional":{"show":"","when":null,"eq":""},"validate":{"required":false,"minLength":0,"maxLength":50,"pattern":"","custom":"","customPrivate":false},"clearOnHide":false,"hidden":false,"persistent":true,"unique":false,"protected":false,"defaultValue":"","multiple":false,"suffix":"","prefix":"","placeholder":"","key":"middleName","label":"middleName","inputMask":"","inputType":"text","tableView":true,"input":true,"lockKey":true,"hideLabel":false,"autofocus":false,"spellcheck":true,"labelPosition":"top","inputFormat":"plain"}],"width":4,"offset":0,"push":0,"pull":0},{"components":[{"properties":{"":""},"tags":[],"type":"textfield","conditional":{"show":"","when":null,"eq":""},"validate":{"required":true,"minLength":0,"maxLength":50,"pattern":"","custom":"","customPrivate":false},"clearOnHide":false,"hidden":false,"persistent":true,"unique":false,"protected":false,"defaultValue":"","multiple":false,"suffix":"","prefix":"","placeholder":"","key":"lastName","label":"lastName","inputMask":"","inputType":"text","tableView":true,"input":true,"lockKey":true,"hideLabel":false,"autofocus":false,"spellcheck":true,"labelPosition":"top","inputFormat":"plain"}],"width":4,"offset":0,"push":0,"pull":0}],"label":"Columns"},{"properties":{"":""},"conditional":{"show":"","when":null,"eq":""},"tags":[],"type":"columns","key":"wellColumns3","tableView":false,"input":false,"clearOnHide":false,"hideLabel":false,"columns":[{"components":[{"input":true,"tableView":true,"inputType":"text","inputMask":"999-99-9999","label":"sSN","key":"sSN","placeholder":"","prefix":"","suffix":"","multiple":false,"defaultValue":"","protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":false,"validate":{"customPrivate":false,"custom":"var SSN_REGEXP = /^(?!\\b(\\d)\\1+-(\\d)\\1+-(\\d)\\1+\\b)(?!123-45-6789|219-09-9999|078-05-1120)(?!666|000|9\\d{2})\\d{3}-(?!00)\\d{2}-(?!0{4})\\d{4}$/g;\nvar td = SSN_REGEXP.test(input);\nif(!td)\n{\nvalid = \"Invalid SSN\";\n}\nelse\n{\nvalid = true;\n}","pattern":"","maxLength":"","minLength":"","required":true},"conditional":{"eq":"","when":null,"show":""},"type":"textfield","tags":[],"properties":{"":""},"lockKey":true,"hideLabel":false,"labelPosition":"top","customError":"Invalid SSN","autofocus":false,"spellcheck":true,"inputFormat":"plain"}],"width":6,"offset":0,"push":0,"pull":0},{"components":[{"input":true,"tableView":true,"label":"gender","key":"gender","placeholder":"","data":{"values":[{"value":"male","label":"Male"},{"value":"female","label":"Female"}],"json":"","url":"","resource":"","custom":""},"dataSrc":"values","valueProperty":"","defaultValue":"","refreshOn":"","filter":"","authenticate":false,"template":"<span>{{ item.label }}</span>","multiple":false,"protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":false,"validate":{"required":true},"type":"select","hideLabel":false,"labelPosition":"top","tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{"":""},"lockKey":true,"autofocus":false}],"width":6,"offset":0,"push":0,"pull":0}],"label":"Columns"},{"clearOnHide":false,"label":"Columns","input":false,"tableView":false,"key":"wellColumns4","columns":[{"components":[{"autofocus":false,"input":true,"tableView":true,"label":"dateOfBirth","key":"dateOfBirth","fields":{"day":{"type":"number","placeholder":"","required":false},"month":{"type":"select","placeholder":"","required":false},"year":{"type":"number","placeholder":"","required":false}},"dayFirst":false,"protected":false,"persistent":true,"hidden":false,"clearOnHide":false,"validate":{"custom":"if(input){\n     if (input == '00/00/0000') {\n        valid = 'Required';\n    } else {\n        var x = input.split('/');\n        var m = parseInt(x[0]);\n        var d = parseInt(x[1])\n        var y = parseInt(x[2]);\n\n        if (m >= 1 && m <= 12) {\n            if (y >= 1900 && y < 2079) {\n               if (d >= 1 && d <= 31) {\n                valid = true;\n               }\n               else{\n                 valid = 'Invalid date';\n               }\n            } else {\n                valid = 'Date range must be from 1900 to 2078';\n            }\n        } else {\n            valid = 'Invalid date';\n        }\n    }\n}\nelse{\n  valid = 'Required';\n}"},"type":"day","labelPosition":"top","inputsLabelPosition":"top","tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{},"lockKey":true,"useLocaleSettings":false,"customError":"Date range must be from 1900 to 2078"}],"width":12,"offset":0,"push":0,"pull":0}],"type":"columns","hideLabel":true,"tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{}},{"properties":{"":""},"conditional":{"eq":"","when":null,"show":""},"tags":[],"hideLabel":false,"type":"columns","key":"wellColumns2","tableView":false,"input":false,"clearOnHide":false,"columns":[{"components":[{"hideLabel":false,"validate":{"required":false,"customMessage":""},"properties":{"":""},"conditional":{"show":"","when":null,"eq":""},"tags":[],"type":"email","kickbox":{"enabled":false},"clearOnHide":false,"hidden":false,"persistent":true,"unique":false,"protected":false,"defaultValue":"","suffix":"","prefix":"","placeholder":"","key":"email","label":"email","inputType":"email","tableView":true,"input":true,"lockKey":true,"autofocus":false,"labelPosition":"top","inputFormat":"plain"}],"width":6,"offset":0,"push":0,"pull":0},{"components":[{"hideLabel":false,"properties":{"":""},"conditional":{"show":"","when":null,"eq":""},"tags":[],"type":"phoneNumber","validate":{"required":false,"customMessage":""},"clearOnHide":false,"defaultValue":"","hidden":false,"persistent":true,"unique":false,"protected":false,"multiple":false,"suffix":"","prefix":"","placeholder":"","key":"phoneNumber","label":"phoneNumber","inputMask":"(999) 999-9999","tableView":true,"input":true,"inputType":"tel","lockKey":true,"autofocus":false,"labelPosition":"top","inputFormat":"plain","calculateValue":""}],"width":6,"offset":0,"push":0,"pull":0}],"label":"Columns"}]},{"properties":{"":""},"conditional":{"show":"","when":null,"eq":""},"tags":[],"type":"well","tableView":false,"input":false,"key":"well2","clearOnHide":false,"hideLabel":false,"components":[{"properties":{"":""},"conditional":{"show":"","when":null,"eq":""},"tags":[],"type":"columns","key":"well2Columns","tableView":false,"input":false,"clearOnHide":false,"hideLabel":false,"columns":[{"components":[{"properties":{"":""},"tags":[],"type":"textfield","conditional":{"show":"","when":null,"eq":""},"validate":{"required":true,"minLength":0,"maxLength":50,"pattern":"","custom":"","customPrivate":false},"clearOnHide":false,"hidden":false,"persistent":true,"unique":false,"protected":false,"defaultValue":"","multiple":false,"suffix":"","prefix":"","placeholder":"","key":"address1","label":"address1","inputMask":"","inputType":"text","tableView":true,"input":true,"lockKey":true,"hideLabel":false,"autofocus":false,"spellcheck":true,"labelPosition":"top","inputFormat":"plain"}],"width":6,"offset":0,"push":0,"pull":0},{"components":[{"properties":{"":""},"tags":[],"type":"textfield","conditional":{"show":"","when":null,"eq":""},"validate":{"required":false,"minLength":0,"maxLength":50,"pattern":"","custom":"","customPrivate":false},"clearOnHide":false,"hidden":false,"persistent":true,"unique":false,"protected":false,"defaultValue":"","multiple":false,"suffix":"","prefix":"","placeholder":"","key":"address2","label":"aptSteLot","inputMask":"","inputType":"text","tableView":true,"input":true,"hideLabel":false,"autofocus":false,"spellcheck":true,"labelPosition":"top","inputFormat":"plain","lockKey":true}],"width":6,"offset":0,"push":0,"pull":0}],"label":"Columns"},{"properties":{"":""},"conditional":{"show":"","when":null,"eq":""},"tags":[],"type":"columns","key":"well2Columns2","tableView":false,"input":false,"clearOnHide":false,"hideLabel":false,"columns":[{"components":[{"properties":{"":""},"tags":[],"type":"textfield","conditional":{"show":"","when":null,"eq":""},"validate":{"required":true,"minLength":0,"maxLength":25,"pattern":"","custom":"","customPrivate":false},"clearOnHide":false,"hidden":false,"persistent":true,"unique":false,"protected":false,"defaultValue":"","multiple":false,"suffix":"","prefix":"","placeholder":"","key":"city","label":"city","inputMask":"","inputType":"text","tableView":true,"input":true,"hideLabel":false,"autofocus":false,"spellcheck":true,"labelPosition":"top","inputFormat":"plain","lockKey":true}],"width":4,"offset":0,"push":0,"pull":0},{"components":[{"labelPosition":"top","properties":{"":""},"conditional":{"eq":"","when":null,"show":""},"tags":[],"type":"select","validate":{"required":true},"clearOnHide":false,"hidden":false,"persistent":true,"unique":false,"protected":false,"multiple":false,"template":"<span>{{ item.label }}</span>","authenticate":false,"filter":"","refreshOn":"","defaultValue":"","valueProperty":"","dataSrc":"values","data":{"custom":"","resource":"","url":"","json":"","values":[{"label":"alabama","value":"AL"},{"label":"alaska","value":"AK"},{"label":"arizona","value":"AZ"},{"label":"arkansas","value":"AR"},{"label":"california","value":"CA"},{"label":"colorado","value":"CO"},{"label":"connecticut","value":"CT"},{"label":"districtofColumbia","value":"DC"},{"label":"delaware","value":"DE"},{"label":"florida","value":"FL"},{"label":"georgia","value":"GA"},{"label":"guan","value":"GU"},{"label":"hawaii","value":"HI"},{"label":"iowa","value":"IA"},{"label":"idaho","value":"ID"},{"label":"illinois","value":"IL"},{"label":"indiana","value":"IN"},{"label":"kansas","value":"KS"},{"label":"kentucky","value":"KY"},{"label":"louisiana","value":"LA"},{"label":"massachusetts","value":"MA"},{"label":"maryland","value":"MD"},{"label":"maine","value":"ME"},{"label":"michigan","value":"MI"},{"label":"minnesota","value":"MN"},{"label":"missouri","value":"MO"},{"label":"mississippi","value":"MS"},{"label":"montana","value":"MT"},{"label":"northCarolina","value":"NC"},{"label":"northDakota","value":"ND"},{"label":"nebraska","value":"NE"},{"label":"newHampshire","value":"NH"},{"label":"newJersey","value":"NJ"},{"label":"newMexico","value":"NM"},{"label":"nevada","value":"NV"},{"label":"newYork","value":"NY"},{"label":"ohio","value":"OH"},{"label":"oklahoma","value":"OK"},{"label":"oregon","value":"OR"},{"label":"pennsylvania","value":"PA"},{"label":"puertoRico","value":"PR"},{"label":"rhodeIsland","value":"RI"},{"label":"southCarolina","value":"SC"},{"label":"southDakota","value":"SD"},{"label":"tennessee","value":"TN"},{"label":"texas","value":"TX"},{"label":"utah","value":"UT"},{"label":"virginia","value":"VA"},{"label":"virginIslands","value":"VI"},{"label":"vermont","value":"VT"},{"label":"washington","value":"WA"},{"label":"wisconsin","value":"WI"},{"value":"WV","label":"westVirginia"},{"value":"WY","label":"wyoming"}]},"placeholder":"","key":"state","label":"state","tableView":true,"input":true,"hideLabel":false,"autofocus":false,"lockKey":true}],"width":4,"offset":0,"push":0,"pull":0},{"components":[{"lockKey":true,"properties":{"":""},"tags":[],"type":"textfield","conditional":{"eq":"","when":null,"show":""},"validate":{"customPrivate":false,"custom":"","pattern":"","maxLength":"","minLength":"","required":true},"clearOnHide":false,"hidden":false,"persistent":true,"unique":false,"protected":false,"defaultValue":"","multiple":false,"suffix":"","prefix":"","placeholder":"","key":"zIP","label":"zIPCode","inputMask":"99999","inputType":"text","tableView":true,"input":true,"hideLabel":false,"autofocus":false,"spellcheck":true,"labelPosition":"top","inputFormat":"plain"}],"width":4,"offset":0,"push":0,"pull":0}],"label":"Columns"},{"clearOnHide":false,"label":"Columns","input":false,"tableView":false,"key":"well2Columns4","columns":[{"components":[{"autofocus":false,"input":true,"tableView":false,"inputType":"radio","label":"Do you want to opt in to receive text message notifications?","key":"receiveTextNotificationOption","values":[{"value":"yes","label":"yes","shortcut":""},{"value":"no","label":"no","shortcut":""}],"defaultValue":"","protected":false,"fieldSet":false,"persistent":true,"hidden":false,"clearOnHide":false,"validate":{"required":false,"custom":"","customPrivate":false},"type":"radio","labelPosition":"top","optionsLabelPosition":"right","tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{},"inline":false,"labelWidth":null,"labelMargin":null,"lockKey":true,"dataGridLabel":false},{"clearOnHide":false,"label":"Columns","input":false,"tableView":false,"key":"well2Columns3","columns":[{"components":[{"autofocus":false,"input":true,"tableView":true,"inputType":"text","inputMask":"(999) 999-9999","label":"Cell Phone Number","key":"cellPhoneNumber","placeholder":"","prefix":"","suffix":"","multiple":false,"defaultValue":"","protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":false,"spellcheck":true,"validate":{"required":true,"minLength":"","maxLength":"","pattern":"","custom":"","customPrivate":false},"conditional":{"show":"true","when":"receiveTextNotificationOption","eq":"yes"},"type":"textfield","labelPosition":"top","inputFormat":"plain","tags":[],"properties":{},"lockKey":true}],"width":6,"offset":0,"push":0,"pull":0},{"components":[{"autofocus":false,"input":true,"tableView":true,"label":"ficellPhoneServiceProvider","key":"cellPhonesServiceProvider","placeholder":"","data":{"values":[{"value":"","label":""}],"json":"","url":"{{data.apiUrl}}formio/getlistitem?json={\"category\":\"ServiceProvider\", \"officeId\":\"{{data.officeId}}\", \"relatesTo\":\"{{data.relatesTo}}\"}","resource":"","custom":"","headers":[{"value":"","key":""}]},"dataSrc":"url","valueProperty":"","defaultValue":"","refreshOn":"","filter":"","authenticate":false,"template":"<span>{{ item.label }}</span>","multiple":false,"protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":false,"validate":{"required":false},"type":"select","labelPosition":"top","tags":[],"conditional":{"show":"true","when":"receiveTextNotificationOption","eq":"yes"},"properties":{},"lockKey":true}],"width":6,"offset":0,"push":0,"pull":0}],"type":"columns","tags":[],"conditional":{"show":"true","when":"receiveTextNotificationOption","eq":"yes"},"properties":{},"customConditional":"","hideLabel":true}],"width":12,"offset":0,"push":0,"pull":0}],"type":"columns","hideLabel":true,"tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{},"customConditional":"show = (data.hasOwnProperty('insertDate') && data['insertDate']);","isNew":false}]},{"autofocus":false,"input":true,"tableView":true,"inputType":"number","label":"validationNumber","key":"validationNumber","placeholder":"","prefix":"","suffix":"","defaultValue":"","protected":false,"persistent":true,"hidden":true,"clearOnHide":false,"validate":{"required":false,"min":null,"max":"","step":"any","integer":"","multiple":"","custom":"valid = (input > 0)? true : 'Email or Phone Number is required.';","customMessage":""},"type":"number","labelPosition":"top","tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{},"calculateValue":"value = 0;\n\nif(data['email']){\n   value= value + 1;\n}\n\nif(data['phoneNumber']){\n   value= value + 1;\n}","lockKey":true,"customError":"Email or Phone Number is required."},{"customClass":"formio-submit-btn formio-ESG-submit-btn","properties":{"":""},"conditional":{"show":"","when":null,"eq":""},"tags":[],"type":"button","theme":"primary","disableOnInvalid":false,"action":"submit","block":false,"rightIcon":"","leftIcon":"","size":"md","key":"submit","tableView":false,"label":"Submit","input":true,"hideLabel":false,"autofocus":false}],"revisions":"","_vid":0,"_id":"5d6f5b3802605815ac7d703d","title":"rubanNewhireInformationTest","display":"form","access":[{"roles":[],"type":"create_own"},{"roles":[],"type":"create_all"},{"roles":["5988294e8db490000695c4fe"],"type":"read_own"},{"roles":["5988294e8db490000695c4fc","5988294e8db490000695c4fd","5988294e8db490000695c4fe"],"type":"read_all"},{"roles":["5988294e8db490000695c4fe"],"type":"update_own"},{"roles":["5988294e8db490000695c4fe"],"type":"update_all"},{"roles":["5988294e8db490000695c4fe"],"type":"delete_own"},{"roles":["5988294e8db490000695c4fe"],"type":"delete_all"},{"roles":[],"type":"team_read"},{"roles":[],"type":"team_write"},{"roles":[],"type":"team_admin"}],"submissionAccess":[{"roles":["5988294e8db490000695c4fe"],"type":"create_own"},{"roles":["5988294e8db490000695c4fe"],"type":"create_all"},{"roles":["5988294e8db490000695c4fe"],"type":"read_own"},{"roles":["5988294e8db490000695c4fe"],"type":"read_all"},{"roles":["5988294e8db490000695c4fe"],"type":"update_own"},{"roles":["5988294e8db490000695c4fe"],"type":"update_all"},{"roles":["5988294e8db490000695c4fe"],"type":"delete_own"},{"roles":["5988294e8db490000695c4fe"],"type":"delete_all"},{"roles":[],"type":"team_read"},{"roles":[],"type":"team_write"},{"roles":[],"type":"team_admin"}],"settings":{},"properties":{},"name":"rubanNewhireInformationTest","path":"rubannewhireinformationtest","project":"5988294e8db490000695c4fb","created":"2019-09-04T06:35:36.094Z","modified":"2019-09-04T07:21:59.546Z","machineName":"cxvbtvxzovojwgq:rubanNewhireInformationTest"}

**Comment by aiwebb** [comment] 2019-09-04 20:40
@rubandangol, that doesn't appear to be valid JSON - can you take another look?

**Comment by randallknutson** [comment] 2019-09-04 20:41
This might be because in bootstrap 4 we are using sm classes for columns. You can see this here: https://github.com/formio/formio.js/blob/4.x/src/templates/bootstrap/columns/form.ejs

You can try overriding the template code with information from https://github.com/formio/formio.js/wiki/Form-Templating#overriding-templates

**Comment by rubandangol** [comment] 2019-09-05 00:51
@aiwebb Apologies for the invalid json. I'll send the form url insted. Here you go: https://icrozsqyopphsot.form.io/testnewhireinfo

@randallknutson Overriding templates are kind of new to me. I will try regardless. However, I would expect it to be mobile friendly without me having to do overwrite anything since it used to work when using bootstrap 3.

**Comment by randallknutson** [comment] 2019-09-05 14:44
It should be mobile friendly by design. I think we just picked the wrong breakpoint for bootstrap 4 so it isn't actually breaking on small screens. This may be as simple to fix as switching out "sm" for "md" in that template.

**Comment by randallknutson** [comment] 2019-09-05 21:22
https://github.com/formio/formio.js/pull/1635

**Comment by sabinayakc** [comment] 2019-10-01 18:23
I am having the same issue but using angular-formio.

**Comment by travist** [comment] 2019-10-28 15:47
Should be fixed. Please verify.

**Closed by travist** 2019-10-28 15:47 UTC
Labels: bug
