### ISSUE TITLE
[BUG] cyrillic letters in labels

### ISSUE THREAD

**Issue by onmywaytoheaven** [formio/formio.js#1631] opened 2019-09-04 18:04 UTC
Hello!
Found this bug in https://github.com/novacode-nl/odoo-formio/issues/6
## Environment
- Browser: Firefox
- Browser version: 68.0.2

## Steps to Reproduce
1. Go to https://formio.github.io/formio.js/app/builder
2. Place field that have label (e.g. Text Field)
3. Add one or more cyrillic letters to label
4. Click Save

## Expected behavior
Form saved and closed

## Observed behavior
Nothing happend
## Example
![formio_cyrillic_bug](https://user-images.githubusercontent.com/43062804/64279262-4e0ba080-cf57-11e9-9407-f495bd52308e.gif)

**Comment by jhen1422** [comment] 2019-09-04 21:04
@onmywaytoheaven 
Thank you for the report. We have added this item to our platform backlog. If you are needing this fix expedited, please contact support@form.io for pricing information

**Comment by bobslee** [comment] 2019-09-05 09:00
Hi,
This issue occurs with (strandalone) **Form.io Javascript client**, without the backend/platform.
So I guess the issue isn't related with your backend/platform.

It can easily be reproduced :)

**Comment by heather-formio** [comment] 2022-10-12 13:08
I tested this with 4.14.9 and it is working as expected. Closing thread, please reopen if needed. Thank you for your contributions!

**Closed by heather-formio** 2022-10-12 13:08 UTC
Labels: bug
