### ISSUE TITLE
[BUG] Sketchpad not styled correctly when rendered via Formio.createForm

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#4085] opened 2021-05-19 22:09 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Formio.js version: v4.10.5
- Formio premium version: v1.14.0
- Frontend framework: None
- Browser: Chrome
- Browser version: 90.0.4430.212

## Steps to Reproduce
The best I can say is match the versions, and render a form via Formio.createForm

## Expected behavior
When formio renders the sketchpad component, I expect to be able to draw over my background image

## Observed behavior
When formio renders the sketchpad component, the styles for the container which are meant to overlay the svg on top of the background image are not present and consequently the two do not overlay

## Hotfix solution
I copied the styles form the portal via devtools and put them in our stylesheet and it works. I just don't know why those styles aren't coming through. If I recall correctly, the file component is also a premium component and I haven't had trouble with its styling this like

## Example
Unfortunately I cannot provide steps to reproduce via JSFiddle or similar since this requires access to the premium components

**Comment by wag110894** [comment] 2021-05-20 16:53
@SalTor, can you try upgrading your formio.js and premium to see if the issue is resolved?

**Comment by SalTor** [comment] 2021-05-20 17:27
Hi Will, I did try that and no dice. A support rep over email suggested I make sure I'm importing premium.min.css but I haven't seen documentation indicating from where I would import that file

**Comment by SalTor** [comment] 2021-05-21 20:57
@wag110894 Any advice on what to try next? What I copied from portal.form.io via devtools seems sufficient for desktop but the user experience is insufficient on mobile with the image scrolling and the cursor position often being misaligned with where the user presses on the screen if the scroll is off a littlebit and it's not clear to me whether this is due to lack of styling coming from the package or not or if the sketchpad component wasn't really built for mobile

**Comment by SalTor** [comment] 2021-06-01 14:38
An update on my end: After updating to the latest versions of formiojs and @formio/premium the mobile experience is resolved but I still need to manually copy the styles from portal.form.io

**Comment by SalTor** [comment] 2021-06-11 13:39
@wag110894 Has anyone been able to look into this Premium component to see if it's more likely we're doing something wrong on our end?

**Comment by Tatsiana8** [comment] 2024-02-07 14:45
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by Tatsiana8** 2024-02-07 14:45 UTC
Labels: bug
