### ISSUE TITLE
The size of library is too large

### ISSUE THREAD

**Issue by dheerajsh** [formio/formio.js#1243] opened 2019-05-10 08:43 UTC
Hello Support Team,
I appreciate the effort to make this library and it is very useful.
I am including this library via NPM, but seems to be tightly dependent on core-js lib, both together increasing the size of my app exponentially around 12 MiB (unzipped).
My Application produces a JS file which is going to include on browser page so i can't afford to have a large size.
How I can still use this lib and not increasing the size of my lib?

**Comment by randallknutson** [comment] 2019-05-10 14:40
If you include the files in a build tool like webpack and import the Form component directly instead of the build files it can reduce the size of the builds. That way only the libraries that are needed are included. Here is an example how to do that. https://github.com/formio/react-formio/blob/master/src/components/Form.js

We do need to go back through our library and find the items that are causing the biggest size bloat and either refactor or remove them. The compressed version is currently 1Mb which we'd like to get down to 500k or less.

**Comment by dheerajsh** [comment] 2019-05-14 08:31
Still, the size is large.

**Comment by goat-io** [comment] 2019-05-14 14:21
I agree with @dheerajsh, 1 MB is extremely large if you want to use it on mobile. Recommended chunk size is less than 244kb, so just by importing formiojs you go over it. Just by overlooking at the library and the bundle, you could replace Moment for Dayjs and save around 25% (is more or less a drop-in replacement).
Same with lodash, several of the uses that I've seen so far can be replaced by "raw" ES6. Most of the Clonedeeps and merges can be easily replaced and whenever is extreamly necesary you could just import the function, as now the Base component imports the whole library (line 6 Base.js: import _ from 'lodash';) native-promise-only should not be necesary with babel, etc etc...I'm pretty sure you guys already know all of this, but it takes a lot of work.
I will try to fork the library on Friday and check what can I do to help. @randallknutson should I try working on 4.x or the current 3.X stable version?

**Comment by prashantsail** [comment] 2019-09-23 08:57
Was about to open a new ticket, when I found this one.

I have a webapp and I only use the form renderer (version 3.26.0). I include the formio.form.min.js & formio.form.min.css on my page. I am plan on moving to the latest 4.x version.
The library size though is a major deterrent.

@randallknutson 
> We do need to go back through our library and find the items that are causing the biggest size bloat and either refactor or remove them. The compressed version is currently 1Mb which we'd like to get down to 500k or less.

On the contrary the size has increased in the 4.x version.

Looking at file `dist/formio.form.min.js`

| Version | Size |
| ------- | ----- |
| [3.26.0](https://github.com/formio/formio.js/blob/v3.26.0/dist/formio.form.min.js) | 968KB |
| [3.27.3](https://github.com/formio/formio.js/blob/v3.27.3/dist/formio.form.min.js) | 963KB |
| [4.1.1](https://github.com/formio/formio.js/blob/v4.1.1/dist/formio.form.min.js) | 1.29MB |
|[4.2.0-rc.5](https://github.com/formio/formio.js/blob/v4.2.0-rc.5/dist/formio.form.min.js) (Latest 4.x release as of today)| 1.6MB |

Any plans on taking up this task  ?
In the meanwhile, I am open to any suggestions.

**Comment by travist** [comment] 2019-09-23 19:00
I just found some quick wins for the next build.  https://github.com/formio/formio.js/pull/1736

This gets it back down to 1.2MB.  I believe the jump from 3x to 4x is because we are including all templates.

https://monosnap.com/file/zoBUx2n6jXU6YxT5vAL5S8yjGA1USG

The other big offender is Lodash, which our plan there is to create a Babel shim for Lodash that would end up using core.js for a lot of the features there, but this would probably be a large endeavor we will take at another time.

**Comment by lnorton89** [comment] 2022-12-08 04:47
As this is three years old and not removed off the road map with no indications of progress I'm assuming this library WONTFIX?

**Comment by brendanbond** [comment] 2022-12-08 15:10
> As this is three years old and not removed off the road map with no indications of progress I'm assuming this library WONTFIX?

@lnorton89  There's an initiative underway as we speak to transition the renderer to [a smaller, more performant core](https://github.com/formio/core); the issue is we have a lot of customers that depend on the renderer as-is, so necessarily it is a slow and careful process so we don't break anybody's deployments.

**Comment by Tatsiana8** [comment] 2024-01-31 14:11
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed** 2024-01-31 14:12 UTC
Labels: Roadmap
